// Code generated by ent, DO NOT EDIT.

package invoicerequestorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldLTE(FieldID, id))
}

// InvoiceRequestID applies equality check predicate on the "invoice_request_id" field. It's identical to InvoiceRequestIDEQ.
func InvoiceRequestID(v int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEQ(FieldInvoiceRequestID, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEQ(FieldOrderID, v))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEQ(FieldOrderNo, v))
}

// OrderType applies equality check predicate on the "order_type" field. It's identical to OrderTypeEQ.
func OrderType(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEQ(FieldOrderType, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEQ(FieldName, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEQ(FieldAmount, v))
}

// ReleasedAt applies equality check predicate on the "released_at" field. It's identical to ReleasedAtEQ.
func ReleasedAt(v time.Time) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEQ(FieldReleasedAt, v))
}

// InvoiceRequestIDEQ applies the EQ predicate on the "invoice_request_id" field.
func InvoiceRequestIDEQ(v int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEQ(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDNEQ applies the NEQ predicate on the "invoice_request_id" field.
func InvoiceRequestIDNEQ(v int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldNEQ(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDIn applies the In predicate on the "invoice_request_id" field.
func InvoiceRequestIDIn(vs ...int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldIn(FieldInvoiceRequestID, vs...))
}

// InvoiceRequestIDNotIn applies the NotIn predicate on the "invoice_request_id" field.
func InvoiceRequestIDNotIn(vs ...int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldNotIn(FieldInvoiceRequestID, vs...))
}

// InvoiceRequestIDGT applies the GT predicate on the "invoice_request_id" field.
func InvoiceRequestIDGT(v int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldGT(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDGTE applies the GTE predicate on the "invoice_request_id" field.
func InvoiceRequestIDGTE(v int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldGTE(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDLT applies the LT predicate on the "invoice_request_id" field.
func InvoiceRequestIDLT(v int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldLT(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDLTE applies the LTE predicate on the "invoice_request_id" field.
func InvoiceRequestIDLTE(v int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldLTE(FieldInvoiceRequestID, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v int64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldLTE(FieldOrderID, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldContainsFold(FieldOrderNo, v))
}

// OrderTypeEQ applies the EQ predicate on the "order_type" field.
func OrderTypeEQ(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEQ(FieldOrderType, v))
}

// OrderTypeNEQ applies the NEQ predicate on the "order_type" field.
func OrderTypeNEQ(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldNEQ(FieldOrderType, v))
}

// OrderTypeIn applies the In predicate on the "order_type" field.
func OrderTypeIn(vs ...string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldIn(FieldOrderType, vs...))
}

// OrderTypeNotIn applies the NotIn predicate on the "order_type" field.
func OrderTypeNotIn(vs ...string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldNotIn(FieldOrderType, vs...))
}

// OrderTypeGT applies the GT predicate on the "order_type" field.
func OrderTypeGT(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldGT(FieldOrderType, v))
}

// OrderTypeGTE applies the GTE predicate on the "order_type" field.
func OrderTypeGTE(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldGTE(FieldOrderType, v))
}

// OrderTypeLT applies the LT predicate on the "order_type" field.
func OrderTypeLT(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldLT(FieldOrderType, v))
}

// OrderTypeLTE applies the LTE predicate on the "order_type" field.
func OrderTypeLTE(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldLTE(FieldOrderType, v))
}

// OrderTypeContains applies the Contains predicate on the "order_type" field.
func OrderTypeContains(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldContains(FieldOrderType, v))
}

// OrderTypeHasPrefix applies the HasPrefix predicate on the "order_type" field.
func OrderTypeHasPrefix(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldHasPrefix(FieldOrderType, v))
}

// OrderTypeHasSuffix applies the HasSuffix predicate on the "order_type" field.
func OrderTypeHasSuffix(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldHasSuffix(FieldOrderType, v))
}

// OrderTypeEqualFold applies the EqualFold predicate on the "order_type" field.
func OrderTypeEqualFold(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEqualFold(FieldOrderType, v))
}

// OrderTypeContainsFold applies the ContainsFold predicate on the "order_type" field.
func OrderTypeContainsFold(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldContainsFold(FieldOrderType, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldContainsFold(FieldName, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldLTE(FieldAmount, v))
}

// ReleasedAtEQ applies the EQ predicate on the "released_at" field.
func ReleasedAtEQ(v time.Time) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldEQ(FieldReleasedAt, v))
}

// ReleasedAtNEQ applies the NEQ predicate on the "released_at" field.
func ReleasedAtNEQ(v time.Time) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldNEQ(FieldReleasedAt, v))
}

// ReleasedAtIn applies the In predicate on the "released_at" field.
func ReleasedAtIn(vs ...time.Time) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldIn(FieldReleasedAt, vs...))
}

// ReleasedAtNotIn applies the NotIn predicate on the "released_at" field.
func ReleasedAtNotIn(vs ...time.Time) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldNotIn(FieldReleasedAt, vs...))
}

// ReleasedAtGT applies the GT predicate on the "released_at" field.
func ReleasedAtGT(v time.Time) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldGT(FieldReleasedAt, v))
}

// ReleasedAtGTE applies the GTE predicate on the "released_at" field.
func ReleasedAtGTE(v time.Time) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldGTE(FieldReleasedAt, v))
}

// ReleasedAtLT applies the LT predicate on the "released_at" field.
func ReleasedAtLT(v time.Time) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldLT(FieldReleasedAt, v))
}

// ReleasedAtLTE applies the LTE predicate on the "released_at" field.
func ReleasedAtLTE(v time.Time) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldLTE(FieldReleasedAt, v))
}

// ReleasedAtIsNil applies the IsNil predicate on the "released_at" field.
func ReleasedAtIsNil() predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldIsNull(FieldReleasedAt))
}

// ReleasedAtNotNil applies the NotNil predicate on the "released_at" field.
func ReleasedAtNotNil() predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.FieldNotNull(FieldReleasedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceRequestOrder) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceRequestOrder) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceRequestOrder) predicate.InvoiceRequestOrder {
	return predicate.InvoiceRequestOrder(sql.NotPredicates(p))
}
