// Code generated by ent, DO NOT EDIT.

package subscriptiondiscountcode

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the subscriptiondiscountcode type in the database.
	Label = "subscription_discount_code"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldDiscountType holds the string denoting the discount_type field in the database.
	FieldDiscountType = "discount_type"
	// FieldDiscountValue holds the string denoting the discount_value field in the database.
	FieldDiscountValue = "discount_value"
	// FieldPlanIds holds the string denoting the plan_ids field in the database.
	FieldPlanIds = "plan_ids"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldMaxUses holds the string denoting the max_uses field in the database.
	FieldMaxUses = "max_uses"
	// FieldPerUserLimit holds the string denoting the per_user_limit field in the database.
	FieldPerUserLimit = "per_user_limit"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the subscriptiondiscountcode in the database.
	Table = "subscription_discount_codes"
)

// Columns holds all SQL columns for subscriptiondiscountcode fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldDiscountType,
	FieldDiscountValue,
	FieldPlanIds,
	FieldEnabled,
	FieldExpiresAt,
	FieldMaxUses,
	FieldPerUserLimit,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DiscountTypeValidator is a validator for the "discount_type" field. It is called by the builders before save.
	DiscountTypeValidator func(string) error
	// DefaultPlanIds holds the default value on creation for the "plan_ids" field.
	DefaultPlanIds []int64
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultMaxUses holds the default value on creation for the "max_uses" field.
	DefaultMaxUses int
	// MaxUsesValidator is a validator for the "max_uses" field. It is called by the builders before save.
	MaxUsesValidator func(int) error
	// DefaultPerUserLimit holds the default value on creation for the "per_user_limit" field.
	DefaultPerUserLimit int
	// PerUserLimitValidator is a validator for the "per_user_limit" field. It is called by the builders before save.
	PerUserLimitValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the SubscriptionDiscountCode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByDiscountType orders the results by the discount_type field.
func ByDiscountType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscountType, opts...).ToFunc()
}

// ByDiscountValue orders the results by the discount_value field.
func ByDiscountValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscountValue, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByMaxUses orders the results by the max_uses field.
func ByMaxUses(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxUses, opts...).ToFunc()
}

// ByPerUserLimit orders the results by the per_user_limit field.
func ByPerUserLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPerUserLimit, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
