// Code generated by ent, DO NOT EDIT.

package subscriptiondiscountcode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldCode, v))
}

// DiscountType applies equality check predicate on the "discount_type" field. It's identical to DiscountTypeEQ.
func DiscountType(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldDiscountType, v))
}

// DiscountValue applies equality check predicate on the "discount_value" field. It's identical to DiscountValueEQ.
func DiscountValue(v float64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldDiscountValue, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldEnabled, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldExpiresAt, v))
}

// MaxUses applies equality check predicate on the "max_uses" field. It's identical to MaxUsesEQ.
func MaxUses(v int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldMaxUses, v))
}

// PerUserLimit applies equality check predicate on the "per_user_limit" field. It's identical to PerUserLimitEQ.
func PerUserLimit(v int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldPerUserLimit, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldContainsFold(FieldCode, v))
}

// DiscountTypeEQ applies the EQ predicate on the "discount_type" field.
func DiscountTypeEQ(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldDiscountType, v))
}

// DiscountTypeNEQ applies the NEQ predicate on the "discount_type" field.
func DiscountTypeNEQ(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNEQ(FieldDiscountType, v))
}

// DiscountTypeIn applies the In predicate on the "discount_type" field.
func DiscountTypeIn(vs ...string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldIn(FieldDiscountType, vs...))
}

// DiscountTypeNotIn applies the NotIn predicate on the "discount_type" field.
func DiscountTypeNotIn(vs ...string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNotIn(FieldDiscountType, vs...))
}

// DiscountTypeGT applies the GT predicate on the "discount_type" field.
func DiscountTypeGT(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGT(FieldDiscountType, v))
}

// DiscountTypeGTE applies the GTE predicate on the "discount_type" field.
func DiscountTypeGTE(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGTE(FieldDiscountType, v))
}

// DiscountTypeLT applies the LT predicate on the "discount_type" field.
func DiscountTypeLT(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLT(FieldDiscountType, v))
}

// DiscountTypeLTE applies the LTE predicate on the "discount_type" field.
func DiscountTypeLTE(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLTE(FieldDiscountType, v))
}

// DiscountTypeContains applies the Contains predicate on the "discount_type" field.
func DiscountTypeContains(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldContains(FieldDiscountType, v))
}

// DiscountTypeHasPrefix applies the HasPrefix predicate on the "discount_type" field.
func DiscountTypeHasPrefix(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldHasPrefix(FieldDiscountType, v))
}

// DiscountTypeHasSuffix applies the HasSuffix predicate on the "discount_type" field.
func DiscountTypeHasSuffix(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldHasSuffix(FieldDiscountType, v))
}

// DiscountTypeEqualFold applies the EqualFold predicate on the "discount_type" field.
func DiscountTypeEqualFold(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEqualFold(FieldDiscountType, v))
}

// DiscountTypeContainsFold applies the ContainsFold predicate on the "discount_type" field.
func DiscountTypeContainsFold(v string) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldContainsFold(FieldDiscountType, v))
}

// DiscountValueEQ applies the EQ predicate on the "discount_value" field.
func DiscountValueEQ(v float64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldDiscountValue, v))
}

// DiscountValueNEQ applies the NEQ predicate on the "discount_value" field.
func DiscountValueNEQ(v float64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNEQ(FieldDiscountValue, v))
}

// DiscountValueIn applies the In predicate on the "discount_value" field.
func DiscountValueIn(vs ...float64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldIn(FieldDiscountValue, vs...))
}

// DiscountValueNotIn applies the NotIn predicate on the "discount_value" field.
func DiscountValueNotIn(vs ...float64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNotIn(FieldDiscountValue, vs...))
}

// DiscountValueGT applies the GT predicate on the "discount_value" field.
func DiscountValueGT(v float64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGT(FieldDiscountValue, v))
}

// DiscountValueGTE applies the GTE predicate on the "discount_value" field.
func DiscountValueGTE(v float64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGTE(FieldDiscountValue, v))
}

// DiscountValueLT applies the LT predicate on the "discount_value" field.
func DiscountValueLT(v float64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLT(FieldDiscountValue, v))
}

// DiscountValueLTE applies the LTE predicate on the "discount_value" field.
func DiscountValueLTE(v float64) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLTE(FieldDiscountValue, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNEQ(FieldEnabled, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNotNull(FieldExpiresAt))
}

// MaxUsesEQ applies the EQ predicate on the "max_uses" field.
func MaxUsesEQ(v int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldMaxUses, v))
}

// MaxUsesNEQ applies the NEQ predicate on the "max_uses" field.
func MaxUsesNEQ(v int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNEQ(FieldMaxUses, v))
}

// MaxUsesIn applies the In predicate on the "max_uses" field.
func MaxUsesIn(vs ...int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldIn(FieldMaxUses, vs...))
}

// MaxUsesNotIn applies the NotIn predicate on the "max_uses" field.
func MaxUsesNotIn(vs ...int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNotIn(FieldMaxUses, vs...))
}

// MaxUsesGT applies the GT predicate on the "max_uses" field.
func MaxUsesGT(v int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGT(FieldMaxUses, v))
}

// MaxUsesGTE applies the GTE predicate on the "max_uses" field.
func MaxUsesGTE(v int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGTE(FieldMaxUses, v))
}

// MaxUsesLT applies the LT predicate on the "max_uses" field.
func MaxUsesLT(v int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLT(FieldMaxUses, v))
}

// MaxUsesLTE applies the LTE predicate on the "max_uses" field.
func MaxUsesLTE(v int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLTE(FieldMaxUses, v))
}

// PerUserLimitEQ applies the EQ predicate on the "per_user_limit" field.
func PerUserLimitEQ(v int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldPerUserLimit, v))
}

// PerUserLimitNEQ applies the NEQ predicate on the "per_user_limit" field.
func PerUserLimitNEQ(v int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNEQ(FieldPerUserLimit, v))
}

// PerUserLimitIn applies the In predicate on the "per_user_limit" field.
func PerUserLimitIn(vs ...int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldIn(FieldPerUserLimit, vs...))
}

// PerUserLimitNotIn applies the NotIn predicate on the "per_user_limit" field.
func PerUserLimitNotIn(vs ...int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNotIn(FieldPerUserLimit, vs...))
}

// PerUserLimitGT applies the GT predicate on the "per_user_limit" field.
func PerUserLimitGT(v int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGT(FieldPerUserLimit, v))
}

// PerUserLimitGTE applies the GTE predicate on the "per_user_limit" field.
func PerUserLimitGTE(v int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGTE(FieldPerUserLimit, v))
}

// PerUserLimitLT applies the LT predicate on the "per_user_limit" field.
func PerUserLimitLT(v int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLT(FieldPerUserLimit, v))
}

// PerUserLimitLTE applies the LTE predicate on the "per_user_limit" field.
func PerUserLimitLTE(v int) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLTE(FieldPerUserLimit, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionDiscountCode) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionDiscountCode) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionDiscountCode) predicate.SubscriptionDiscountCode {
	return predicate.SubscriptionDiscountCode(sql.NotPredicates(p))
}
