// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invitebinding"
	"github.com/Wei-Shaw/sub2api/ent/invitecode"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InviteCodeCreate is the builder for creating a InviteCode entity.
type InviteCodeCreate struct {
	config
	mutation *InviteCodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *InviteCodeCreate) SetUserID(v int64) *InviteCodeCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *InviteCodeCreate) SetCode(v string) *InviteCodeCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *InviteCodeCreate) SetActive(v bool) *InviteCodeCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *InviteCodeCreate) SetNillableActive(v *bool) *InviteCodeCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InviteCodeCreate) SetCreatedAt(v time.Time) *InviteCodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InviteCodeCreate) SetNillableCreatedAt(v *time.Time) *InviteCodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InviteCodeCreate) SetUpdatedAt(v time.Time) *InviteCodeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InviteCodeCreate) SetNillableUpdatedAt(v *time.Time) *InviteCodeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *InviteCodeCreate) SetUser(v *User) *InviteCodeCreate {
	return _c.SetUserID(v.ID)
}

// AddBindingIDs adds the "bindings" edge to the InviteBinding entity by IDs.
func (_c *InviteCodeCreate) AddBindingIDs(ids ...int64) *InviteCodeCreate {
	_c.mutation.AddBindingIDs(ids...)
	return _c
}

// AddBindings adds the "bindings" edges to the InviteBinding entity.
func (_c *InviteCodeCreate) AddBindings(v ...*InviteBinding) *InviteCodeCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBindingIDs(ids...)
}

// Mutation returns the InviteCodeMutation object of the builder.
func (_c *InviteCodeCreate) Mutation() *InviteCodeMutation {
	return _c.mutation
}

// Save creates the InviteCode in the database.
func (_c *InviteCodeCreate) Save(ctx context.Context) (*InviteCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InviteCodeCreate) SaveX(ctx context.Context) *InviteCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InviteCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InviteCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InviteCodeCreate) defaults() {
	if _, ok := _c.mutation.Active(); !ok {
		v := invitecode.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invitecode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := invitecode.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InviteCodeCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InviteCode.user_id"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "InviteCode.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := invitecode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "InviteCode.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "InviteCode.active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InviteCode.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InviteCode.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "InviteCode.user"`)}
	}
	return nil
}

func (_c *InviteCodeCreate) sqlSave(ctx context.Context) (*InviteCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InviteCodeCreate) createSpec() (*InviteCode, *sqlgraph.CreateSpec) {
	var (
		_node = &InviteCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invitecode.Table, sqlgraph.NewFieldSpec(invitecode.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(invitecode.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(invitecode.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invitecode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invitecode.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitecode.UserTable,
			Columns: []string{invitecode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invitecode.BindingsTable,
			Columns: []string{invitecode.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitebinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InviteCode.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InviteCodeUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InviteCodeCreate) OnConflict(opts ...sql.ConflictOption) *InviteCodeUpsertOne {
	_c.conflict = opts
	return &InviteCodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InviteCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InviteCodeCreate) OnConflictColumns(columns ...string) *InviteCodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InviteCodeUpsertOne{
		create: _c,
	}
}

type (
	// InviteCodeUpsertOne is the builder for "upsert"-ing
	//  one InviteCode node.
	InviteCodeUpsertOne struct {
		create *InviteCodeCreate
	}

	// InviteCodeUpsert is the "OnConflict" setter.
	InviteCodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *InviteCodeUpsert) SetUserID(v int64) *InviteCodeUpsert {
	u.Set(invitecode.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InviteCodeUpsert) UpdateUserID() *InviteCodeUpsert {
	u.SetExcluded(invitecode.FieldUserID)
	return u
}

// SetCode sets the "code" field.
func (u *InviteCodeUpsert) SetCode(v string) *InviteCodeUpsert {
	u.Set(invitecode.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *InviteCodeUpsert) UpdateCode() *InviteCodeUpsert {
	u.SetExcluded(invitecode.FieldCode)
	return u
}

// SetActive sets the "active" field.
func (u *InviteCodeUpsert) SetActive(v bool) *InviteCodeUpsert {
	u.Set(invitecode.FieldActive, v)
	return u
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *InviteCodeUpsert) UpdateActive() *InviteCodeUpsert {
	u.SetExcluded(invitecode.FieldActive)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InviteCodeUpsert) SetUpdatedAt(v time.Time) *InviteCodeUpsert {
	u.Set(invitecode.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InviteCodeUpsert) UpdateUpdatedAt() *InviteCodeUpsert {
	u.SetExcluded(invitecode.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InviteCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InviteCodeUpsertOne) UpdateNewValues() *InviteCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invitecode.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InviteCode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InviteCodeUpsertOne) Ignore() *InviteCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InviteCodeUpsertOne) DoNothing() *InviteCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InviteCodeCreate.OnConflict
// documentation for more info.
func (u *InviteCodeUpsertOne) Update(set func(*InviteCodeUpsert)) *InviteCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InviteCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InviteCodeUpsertOne) SetUserID(v int64) *InviteCodeUpsertOne {
	return u.Update(func(s *InviteCodeUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InviteCodeUpsertOne) UpdateUserID() *InviteCodeUpsertOne {
	return u.Update(func(s *InviteCodeUpsert) {
		s.UpdateUserID()
	})
}

// SetCode sets the "code" field.
func (u *InviteCodeUpsertOne) SetCode(v string) *InviteCodeUpsertOne {
	return u.Update(func(s *InviteCodeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *InviteCodeUpsertOne) UpdateCode() *InviteCodeUpsertOne {
	return u.Update(func(s *InviteCodeUpsert) {
		s.UpdateCode()
	})
}

// SetActive sets the "active" field.
func (u *InviteCodeUpsertOne) SetActive(v bool) *InviteCodeUpsertOne {
	return u.Update(func(s *InviteCodeUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *InviteCodeUpsertOne) UpdateActive() *InviteCodeUpsertOne {
	return u.Update(func(s *InviteCodeUpsert) {
		s.UpdateActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InviteCodeUpsertOne) SetUpdatedAt(v time.Time) *InviteCodeUpsertOne {
	return u.Update(func(s *InviteCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InviteCodeUpsertOne) UpdateUpdatedAt() *InviteCodeUpsertOne {
	return u.Update(func(s *InviteCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InviteCodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InviteCodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InviteCodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InviteCodeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InviteCodeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InviteCodeCreateBulk is the builder for creating many InviteCode entities in bulk.
type InviteCodeCreateBulk struct {
	config
	err      error
	builders []*InviteCodeCreate
	conflict []sql.ConflictOption
}

// Save creates the InviteCode entities in the database.
func (_c *InviteCodeCreateBulk) Save(ctx context.Context) ([]*InviteCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InviteCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InviteCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InviteCodeCreateBulk) SaveX(ctx context.Context) []*InviteCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InviteCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InviteCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InviteCode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InviteCodeUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InviteCodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *InviteCodeUpsertBulk {
	_c.conflict = opts
	return &InviteCodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InviteCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InviteCodeCreateBulk) OnConflictColumns(columns ...string) *InviteCodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InviteCodeUpsertBulk{
		create: _c,
	}
}

// InviteCodeUpsertBulk is the builder for "upsert"-ing
// a bulk of InviteCode nodes.
type InviteCodeUpsertBulk struct {
	create *InviteCodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InviteCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InviteCodeUpsertBulk) UpdateNewValues() *InviteCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invitecode.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InviteCode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InviteCodeUpsertBulk) Ignore() *InviteCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InviteCodeUpsertBulk) DoNothing() *InviteCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InviteCodeCreateBulk.OnConflict
// documentation for more info.
func (u *InviteCodeUpsertBulk) Update(set func(*InviteCodeUpsert)) *InviteCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InviteCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InviteCodeUpsertBulk) SetUserID(v int64) *InviteCodeUpsertBulk {
	return u.Update(func(s *InviteCodeUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InviteCodeUpsertBulk) UpdateUserID() *InviteCodeUpsertBulk {
	return u.Update(func(s *InviteCodeUpsert) {
		s.UpdateUserID()
	})
}

// SetCode sets the "code" field.
func (u *InviteCodeUpsertBulk) SetCode(v string) *InviteCodeUpsertBulk {
	return u.Update(func(s *InviteCodeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *InviteCodeUpsertBulk) UpdateCode() *InviteCodeUpsertBulk {
	return u.Update(func(s *InviteCodeUpsert) {
		s.UpdateCode()
	})
}

// SetActive sets the "active" field.
func (u *InviteCodeUpsertBulk) SetActive(v bool) *InviteCodeUpsertBulk {
	return u.Update(func(s *InviteCodeUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *InviteCodeUpsertBulk) UpdateActive() *InviteCodeUpsertBulk {
	return u.Update(func(s *InviteCodeUpsert) {
		s.UpdateActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InviteCodeUpsertBulk) SetUpdatedAt(v time.Time) *InviteCodeUpsertBulk {
	return u.Update(func(s *InviteCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InviteCodeUpsertBulk) UpdateUpdatedAt() *InviteCodeUpsertBulk {
	return u.Update(func(s *InviteCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InviteCodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InviteCodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InviteCodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InviteCodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
