// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invitebinding"
	"github.com/Wei-Shaw/sub2api/ent/invitecode"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InviteBindingUpdate is the builder for updating InviteBinding entities.
type InviteBindingUpdate struct {
	config
	hooks    []Hook
	mutation *InviteBindingMutation
}

// Where appends a list predicates to the InviteBindingUpdate builder.
func (_u *InviteBindingUpdate) Where(ps ...predicate.InviteBinding) *InviteBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInviterUserID sets the "inviter_user_id" field.
func (_u *InviteBindingUpdate) SetInviterUserID(v int64) *InviteBindingUpdate {
	_u.mutation.SetInviterUserID(v)
	return _u
}

// SetNillableInviterUserID sets the "inviter_user_id" field if the given value is not nil.
func (_u *InviteBindingUpdate) SetNillableInviterUserID(v *int64) *InviteBindingUpdate {
	if v != nil {
		_u.SetInviterUserID(*v)
	}
	return _u
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (_u *InviteBindingUpdate) SetInviteeUserID(v int64) *InviteBindingUpdate {
	_u.mutation.SetInviteeUserID(v)
	return _u
}

// SetNillableInviteeUserID sets the "invitee_user_id" field if the given value is not nil.
func (_u *InviteBindingUpdate) SetNillableInviteeUserID(v *int64) *InviteBindingUpdate {
	if v != nil {
		_u.SetInviteeUserID(*v)
	}
	return _u
}

// SetInviteCodeID sets the "invite_code_id" field.
func (_u *InviteBindingUpdate) SetInviteCodeID(v int64) *InviteBindingUpdate {
	_u.mutation.SetInviteCodeID(v)
	return _u
}

// SetNillableInviteCodeID sets the "invite_code_id" field if the given value is not nil.
func (_u *InviteBindingUpdate) SetNillableInviteCodeID(v *int64) *InviteBindingUpdate {
	if v != nil {
		_u.SetInviteCodeID(*v)
	}
	return _u
}

// SetInviterID sets the "inviter" edge to the User entity by ID.
func (_u *InviteBindingUpdate) SetInviterID(id int64) *InviteBindingUpdate {
	_u.mutation.SetInviterID(id)
	return _u
}

// SetInviter sets the "inviter" edge to the User entity.
func (_u *InviteBindingUpdate) SetInviter(v *User) *InviteBindingUpdate {
	return _u.SetInviterID(v.ID)
}

// SetInviteeID sets the "invitee" edge to the User entity by ID.
func (_u *InviteBindingUpdate) SetInviteeID(id int64) *InviteBindingUpdate {
	_u.mutation.SetInviteeID(id)
	return _u
}

// SetInvitee sets the "invitee" edge to the User entity.
func (_u *InviteBindingUpdate) SetInvitee(v *User) *InviteBindingUpdate {
	return _u.SetInviteeID(v.ID)
}

// SetInviteCode sets the "invite_code" edge to the InviteCode entity.
func (_u *InviteBindingUpdate) SetInviteCode(v *InviteCode) *InviteBindingUpdate {
	return _u.SetInviteCodeID(v.ID)
}

// Mutation returns the InviteBindingMutation object of the builder.
func (_u *InviteBindingUpdate) Mutation() *InviteBindingMutation {
	return _u.mutation
}

// ClearInviter clears the "inviter" edge to the User entity.
func (_u *InviteBindingUpdate) ClearInviter() *InviteBindingUpdate {
	_u.mutation.ClearInviter()
	return _u
}

// ClearInvitee clears the "invitee" edge to the User entity.
func (_u *InviteBindingUpdate) ClearInvitee() *InviteBindingUpdate {
	_u.mutation.ClearInvitee()
	return _u
}

// ClearInviteCode clears the "invite_code" edge to the InviteCode entity.
func (_u *InviteBindingUpdate) ClearInviteCode() *InviteBindingUpdate {
	_u.mutation.ClearInviteCode()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InviteBindingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InviteBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InviteBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InviteBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InviteBindingUpdate) check() error {
	if _u.mutation.InviterCleared() && len(_u.mutation.InviterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InviteBinding.inviter"`)
	}
	if _u.mutation.InviteeCleared() && len(_u.mutation.InviteeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InviteBinding.invitee"`)
	}
	if _u.mutation.InviteCodeCleared() && len(_u.mutation.InviteCodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InviteBinding.invite_code"`)
	}
	return nil
}

func (_u *InviteBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitebinding.Table, invitebinding.Columns, sqlgraph.NewFieldSpec(invitebinding.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.InviterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitebinding.InviterTable,
			Columns: []string{invitebinding.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitebinding.InviterTable,
			Columns: []string{invitebinding.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InviteeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitebinding.InviteeTable,
			Columns: []string{invitebinding.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitebinding.InviteeTable,
			Columns: []string{invitebinding.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InviteCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitebinding.InviteCodeTable,
			Columns: []string{invitebinding.InviteCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitecode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviteCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitebinding.InviteCodeTable,
			Columns: []string{invitebinding.InviteCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitecode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitebinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InviteBindingUpdateOne is the builder for updating a single InviteBinding entity.
type InviteBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InviteBindingMutation
}

// SetInviterUserID sets the "inviter_user_id" field.
func (_u *InviteBindingUpdateOne) SetInviterUserID(v int64) *InviteBindingUpdateOne {
	_u.mutation.SetInviterUserID(v)
	return _u
}

// SetNillableInviterUserID sets the "inviter_user_id" field if the given value is not nil.
func (_u *InviteBindingUpdateOne) SetNillableInviterUserID(v *int64) *InviteBindingUpdateOne {
	if v != nil {
		_u.SetInviterUserID(*v)
	}
	return _u
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (_u *InviteBindingUpdateOne) SetInviteeUserID(v int64) *InviteBindingUpdateOne {
	_u.mutation.SetInviteeUserID(v)
	return _u
}

// SetNillableInviteeUserID sets the "invitee_user_id" field if the given value is not nil.
func (_u *InviteBindingUpdateOne) SetNillableInviteeUserID(v *int64) *InviteBindingUpdateOne {
	if v != nil {
		_u.SetInviteeUserID(*v)
	}
	return _u
}

// SetInviteCodeID sets the "invite_code_id" field.
func (_u *InviteBindingUpdateOne) SetInviteCodeID(v int64) *InviteBindingUpdateOne {
	_u.mutation.SetInviteCodeID(v)
	return _u
}

// SetNillableInviteCodeID sets the "invite_code_id" field if the given value is not nil.
func (_u *InviteBindingUpdateOne) SetNillableInviteCodeID(v *int64) *InviteBindingUpdateOne {
	if v != nil {
		_u.SetInviteCodeID(*v)
	}
	return _u
}

// SetInviterID sets the "inviter" edge to the User entity by ID.
func (_u *InviteBindingUpdateOne) SetInviterID(id int64) *InviteBindingUpdateOne {
	_u.mutation.SetInviterID(id)
	return _u
}

// SetInviter sets the "inviter" edge to the User entity.
func (_u *InviteBindingUpdateOne) SetInviter(v *User) *InviteBindingUpdateOne {
	return _u.SetInviterID(v.ID)
}

// SetInviteeID sets the "invitee" edge to the User entity by ID.
func (_u *InviteBindingUpdateOne) SetInviteeID(id int64) *InviteBindingUpdateOne {
	_u.mutation.SetInviteeID(id)
	return _u
}

// SetInvitee sets the "invitee" edge to the User entity.
func (_u *InviteBindingUpdateOne) SetInvitee(v *User) *InviteBindingUpdateOne {
	return _u.SetInviteeID(v.ID)
}

// SetInviteCode sets the "invite_code" edge to the InviteCode entity.
func (_u *InviteBindingUpdateOne) SetInviteCode(v *InviteCode) *InviteBindingUpdateOne {
	return _u.SetInviteCodeID(v.ID)
}

// Mutation returns the InviteBindingMutation object of the builder.
func (_u *InviteBindingUpdateOne) Mutation() *InviteBindingMutation {
	return _u.mutation
}

// ClearInviter clears the "inviter" edge to the User entity.
func (_u *InviteBindingUpdateOne) ClearInviter() *InviteBindingUpdateOne {
	_u.mutation.ClearInviter()
	return _u
}

// ClearInvitee clears the "invitee" edge to the User entity.
func (_u *InviteBindingUpdateOne) ClearInvitee() *InviteBindingUpdateOne {
	_u.mutation.ClearInvitee()
	return _u
}

// ClearInviteCode clears the "invite_code" edge to the InviteCode entity.
func (_u *InviteBindingUpdateOne) ClearInviteCode() *InviteBindingUpdateOne {
	_u.mutation.ClearInviteCode()
	return _u
}

// Where appends a list predicates to the InviteBindingUpdate builder.
func (_u *InviteBindingUpdateOne) Where(ps ...predicate.InviteBinding) *InviteBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InviteBindingUpdateOne) Select(field string, fields ...string) *InviteBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InviteBinding entity.
func (_u *InviteBindingUpdateOne) Save(ctx context.Context) (*InviteBinding, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InviteBindingUpdateOne) SaveX(ctx context.Context) *InviteBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InviteBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InviteBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InviteBindingUpdateOne) check() error {
	if _u.mutation.InviterCleared() && len(_u.mutation.InviterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InviteBinding.inviter"`)
	}
	if _u.mutation.InviteeCleared() && len(_u.mutation.InviteeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InviteBinding.invitee"`)
	}
	if _u.mutation.InviteCodeCleared() && len(_u.mutation.InviteCodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InviteBinding.invite_code"`)
	}
	return nil
}

func (_u *InviteBindingUpdateOne) sqlSave(ctx context.Context) (_node *InviteBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitebinding.Table, invitebinding.Columns, sqlgraph.NewFieldSpec(invitebinding.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InviteBinding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invitebinding.FieldID)
		for _, f := range fields {
			if !invitebinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invitebinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.InviterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitebinding.InviterTable,
			Columns: []string{invitebinding.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitebinding.InviterTable,
			Columns: []string{invitebinding.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InviteeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitebinding.InviteeTable,
			Columns: []string{invitebinding.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitebinding.InviteeTable,
			Columns: []string{invitebinding.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InviteCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitebinding.InviteCodeTable,
			Columns: []string{invitebinding.InviteCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitecode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InviteCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitebinding.InviteCodeTable,
			Columns: []string{invitebinding.InviteCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitecode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InviteBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitebinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
