// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/invitebinding"
	"github.com/Wei-Shaw/sub2api/ent/invitecode"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InviteBinding is the model entity for the InviteBinding schema.
type InviteBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// InviterUserID holds the value of the "inviter_user_id" field.
	InviterUserID int64 `json:"inviter_user_id,omitempty"`
	// InviteeUserID holds the value of the "invitee_user_id" field.
	InviteeUserID int64 `json:"invitee_user_id,omitempty"`
	// InviteCodeID holds the value of the "invite_code_id" field.
	InviteCodeID int64 `json:"invite_code_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InviteBindingQuery when eager-loading is set.
	Edges        InviteBindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InviteBindingEdges holds the relations/edges for other nodes in the graph.
type InviteBindingEdges struct {
	// Inviter holds the value of the inviter edge.
	Inviter *User `json:"inviter,omitempty"`
	// Invitee holds the value of the invitee edge.
	Invitee *User `json:"invitee,omitempty"`
	// InviteCode holds the value of the invite_code edge.
	InviteCode *InviteCode `json:"invite_code,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// InviterOrErr returns the Inviter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InviteBindingEdges) InviterOrErr() (*User, error) {
	if e.Inviter != nil {
		return e.Inviter, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "inviter"}
}

// InviteeOrErr returns the Invitee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InviteBindingEdges) InviteeOrErr() (*User, error) {
	if e.Invitee != nil {
		return e.Invitee, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "invitee"}
}

// InviteCodeOrErr returns the InviteCode value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InviteBindingEdges) InviteCodeOrErr() (*InviteCode, error) {
	if e.InviteCode != nil {
		return e.InviteCode, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: invitecode.Label}
	}
	return nil, &NotLoadedError{edge: "invite_code"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InviteBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invitebinding.FieldID, invitebinding.FieldInviterUserID, invitebinding.FieldInviteeUserID, invitebinding.FieldInviteCodeID:
			values[i] = new(sql.NullInt64)
		case invitebinding.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InviteBinding fields.
func (_m *InviteBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invitebinding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invitebinding.FieldInviterUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field inviter_user_id", values[i])
			} else if value.Valid {
				_m.InviterUserID = value.Int64
			}
		case invitebinding.FieldInviteeUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_user_id", values[i])
			} else if value.Valid {
				_m.InviteeUserID = value.Int64
			}
		case invitebinding.FieldInviteCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invite_code_id", values[i])
			} else if value.Valid {
				_m.InviteCodeID = value.Int64
			}
		case invitebinding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InviteBinding.
// This includes values selected through modifiers, order, etc.
func (_m *InviteBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInviter queries the "inviter" edge of the InviteBinding entity.
func (_m *InviteBinding) QueryInviter() *UserQuery {
	return NewInviteBindingClient(_m.config).QueryInviter(_m)
}

// QueryInvitee queries the "invitee" edge of the InviteBinding entity.
func (_m *InviteBinding) QueryInvitee() *UserQuery {
	return NewInviteBindingClient(_m.config).QueryInvitee(_m)
}

// QueryInviteCode queries the "invite_code" edge of the InviteBinding entity.
func (_m *InviteBinding) QueryInviteCode() *InviteCodeQuery {
	return NewInviteBindingClient(_m.config).QueryInviteCode(_m)
}

// Update returns a builder for updating this InviteBinding.
// Note that you need to call InviteBinding.Unwrap() before calling this method if this InviteBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InviteBinding) Update() *InviteBindingUpdateOne {
	return NewInviteBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InviteBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InviteBinding) Unwrap() *InviteBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InviteBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InviteBinding) String() string {
	var builder strings.Builder
	builder.WriteString("InviteBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("inviter_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviterUserID))
	builder.WriteString(", ")
	builder.WriteString("invitee_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviteeUserID))
	builder.WriteString(", ")
	builder.WriteString("invite_code_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviteCodeID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InviteBindings is a parsable slice of InviteBinding.
type InviteBindings []*InviteBinding
