// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invitebinding"
	"github.com/Wei-Shaw/sub2api/ent/invitecode"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InviteBindingCreate is the builder for creating a InviteBinding entity.
type InviteBindingCreate struct {
	config
	mutation *InviteBindingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInviterUserID sets the "inviter_user_id" field.
func (_c *InviteBindingCreate) SetInviterUserID(v int64) *InviteBindingCreate {
	_c.mutation.SetInviterUserID(v)
	return _c
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (_c *InviteBindingCreate) SetInviteeUserID(v int64) *InviteBindingCreate {
	_c.mutation.SetInviteeUserID(v)
	return _c
}

// SetInviteCodeID sets the "invite_code_id" field.
func (_c *InviteBindingCreate) SetInviteCodeID(v int64) *InviteBindingCreate {
	_c.mutation.SetInviteCodeID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InviteBindingCreate) SetCreatedAt(v time.Time) *InviteBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InviteBindingCreate) SetNillableCreatedAt(v *time.Time) *InviteBindingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetInviterID sets the "inviter" edge to the User entity by ID.
func (_c *InviteBindingCreate) SetInviterID(id int64) *InviteBindingCreate {
	_c.mutation.SetInviterID(id)
	return _c
}

// SetInviter sets the "inviter" edge to the User entity.
func (_c *InviteBindingCreate) SetInviter(v *User) *InviteBindingCreate {
	return _c.SetInviterID(v.ID)
}

// SetInviteeID sets the "invitee" edge to the User entity by ID.
func (_c *InviteBindingCreate) SetInviteeID(id int64) *InviteBindingCreate {
	_c.mutation.SetInviteeID(id)
	return _c
}

// SetInvitee sets the "invitee" edge to the User entity.
func (_c *InviteBindingCreate) SetInvitee(v *User) *InviteBindingCreate {
	return _c.SetInviteeID(v.ID)
}

// SetInviteCode sets the "invite_code" edge to the InviteCode entity.
func (_c *InviteBindingCreate) SetInviteCode(v *InviteCode) *InviteBindingCreate {
	return _c.SetInviteCodeID(v.ID)
}

// Mutation returns the InviteBindingMutation object of the builder.
func (_c *InviteBindingCreate) Mutation() *InviteBindingMutation {
	return _c.mutation
}

// Save creates the InviteBinding in the database.
func (_c *InviteBindingCreate) Save(ctx context.Context) (*InviteBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InviteBindingCreate) SaveX(ctx context.Context) *InviteBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InviteBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InviteBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InviteBindingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invitebinding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InviteBindingCreate) check() error {
	if _, ok := _c.mutation.InviterUserID(); !ok {
		return &ValidationError{Name: "inviter_user_id", err: errors.New(`ent: missing required field "InviteBinding.inviter_user_id"`)}
	}
	if _, ok := _c.mutation.InviteeUserID(); !ok {
		return &ValidationError{Name: "invitee_user_id", err: errors.New(`ent: missing required field "InviteBinding.invitee_user_id"`)}
	}
	if _, ok := _c.mutation.InviteCodeID(); !ok {
		return &ValidationError{Name: "invite_code_id", err: errors.New(`ent: missing required field "InviteBinding.invite_code_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InviteBinding.created_at"`)}
	}
	if len(_c.mutation.InviterIDs()) == 0 {
		return &ValidationError{Name: "inviter", err: errors.New(`ent: missing required edge "InviteBinding.inviter"`)}
	}
	if len(_c.mutation.InviteeIDs()) == 0 {
		return &ValidationError{Name: "invitee", err: errors.New(`ent: missing required edge "InviteBinding.invitee"`)}
	}
	if len(_c.mutation.InviteCodeIDs()) == 0 {
		return &ValidationError{Name: "invite_code", err: errors.New(`ent: missing required edge "InviteBinding.invite_code"`)}
	}
	return nil
}

func (_c *InviteBindingCreate) sqlSave(ctx context.Context) (*InviteBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InviteBindingCreate) createSpec() (*InviteBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &InviteBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invitebinding.Table, sqlgraph.NewFieldSpec(invitebinding.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invitebinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.InviterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitebinding.InviterTable,
			Columns: []string{invitebinding.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InviterUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InviteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitebinding.InviteeTable,
			Columns: []string{invitebinding.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InviteeUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InviteCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitebinding.InviteCodeTable,
			Columns: []string{invitebinding.InviteCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitecode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InviteCodeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InviteBinding.Create().
//		SetInviterUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InviteBindingUpsert) {
//			SetInviterUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InviteBindingCreate) OnConflict(opts ...sql.ConflictOption) *InviteBindingUpsertOne {
	_c.conflict = opts
	return &InviteBindingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InviteBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InviteBindingCreate) OnConflictColumns(columns ...string) *InviteBindingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InviteBindingUpsertOne{
		create: _c,
	}
}

type (
	// InviteBindingUpsertOne is the builder for "upsert"-ing
	//  one InviteBinding node.
	InviteBindingUpsertOne struct {
		create *InviteBindingCreate
	}

	// InviteBindingUpsert is the "OnConflict" setter.
	InviteBindingUpsert struct {
		*sql.UpdateSet
	}
)

// SetInviterUserID sets the "inviter_user_id" field.
func (u *InviteBindingUpsert) SetInviterUserID(v int64) *InviteBindingUpsert {
	u.Set(invitebinding.FieldInviterUserID, v)
	return u
}

// UpdateInviterUserID sets the "inviter_user_id" field to the value that was provided on create.
func (u *InviteBindingUpsert) UpdateInviterUserID() *InviteBindingUpsert {
	u.SetExcluded(invitebinding.FieldInviterUserID)
	return u
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (u *InviteBindingUpsert) SetInviteeUserID(v int64) *InviteBindingUpsert {
	u.Set(invitebinding.FieldInviteeUserID, v)
	return u
}

// UpdateInviteeUserID sets the "invitee_user_id" field to the value that was provided on create.
func (u *InviteBindingUpsert) UpdateInviteeUserID() *InviteBindingUpsert {
	u.SetExcluded(invitebinding.FieldInviteeUserID)
	return u
}

// SetInviteCodeID sets the "invite_code_id" field.
func (u *InviteBindingUpsert) SetInviteCodeID(v int64) *InviteBindingUpsert {
	u.Set(invitebinding.FieldInviteCodeID, v)
	return u
}

// UpdateInviteCodeID sets the "invite_code_id" field to the value that was provided on create.
func (u *InviteBindingUpsert) UpdateInviteCodeID() *InviteBindingUpsert {
	u.SetExcluded(invitebinding.FieldInviteCodeID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InviteBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InviteBindingUpsertOne) UpdateNewValues() *InviteBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invitebinding.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InviteBinding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InviteBindingUpsertOne) Ignore() *InviteBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InviteBindingUpsertOne) DoNothing() *InviteBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InviteBindingCreate.OnConflict
// documentation for more info.
func (u *InviteBindingUpsertOne) Update(set func(*InviteBindingUpsert)) *InviteBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InviteBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterUserID sets the "inviter_user_id" field.
func (u *InviteBindingUpsertOne) SetInviterUserID(v int64) *InviteBindingUpsertOne {
	return u.Update(func(s *InviteBindingUpsert) {
		s.SetInviterUserID(v)
	})
}

// UpdateInviterUserID sets the "inviter_user_id" field to the value that was provided on create.
func (u *InviteBindingUpsertOne) UpdateInviterUserID() *InviteBindingUpsertOne {
	return u.Update(func(s *InviteBindingUpsert) {
		s.UpdateInviterUserID()
	})
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (u *InviteBindingUpsertOne) SetInviteeUserID(v int64) *InviteBindingUpsertOne {
	return u.Update(func(s *InviteBindingUpsert) {
		s.SetInviteeUserID(v)
	})
}

// UpdateInviteeUserID sets the "invitee_user_id" field to the value that was provided on create.
func (u *InviteBindingUpsertOne) UpdateInviteeUserID() *InviteBindingUpsertOne {
	return u.Update(func(s *InviteBindingUpsert) {
		s.UpdateInviteeUserID()
	})
}

// SetInviteCodeID sets the "invite_code_id" field.
func (u *InviteBindingUpsertOne) SetInviteCodeID(v int64) *InviteBindingUpsertOne {
	return u.Update(func(s *InviteBindingUpsert) {
		s.SetInviteCodeID(v)
	})
}

// UpdateInviteCodeID sets the "invite_code_id" field to the value that was provided on create.
func (u *InviteBindingUpsertOne) UpdateInviteCodeID() *InviteBindingUpsertOne {
	return u.Update(func(s *InviteBindingUpsert) {
		s.UpdateInviteCodeID()
	})
}

// Exec executes the query.
func (u *InviteBindingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InviteBindingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InviteBindingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InviteBindingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InviteBindingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InviteBindingCreateBulk is the builder for creating many InviteBinding entities in bulk.
type InviteBindingCreateBulk struct {
	config
	err      error
	builders []*InviteBindingCreate
	conflict []sql.ConflictOption
}

// Save creates the InviteBinding entities in the database.
func (_c *InviteBindingCreateBulk) Save(ctx context.Context) ([]*InviteBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InviteBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InviteBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InviteBindingCreateBulk) SaveX(ctx context.Context) []*InviteBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InviteBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InviteBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InviteBinding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InviteBindingUpsert) {
//			SetInviterUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InviteBindingCreateBulk) OnConflict(opts ...sql.ConflictOption) *InviteBindingUpsertBulk {
	_c.conflict = opts
	return &InviteBindingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InviteBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InviteBindingCreateBulk) OnConflictColumns(columns ...string) *InviteBindingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InviteBindingUpsertBulk{
		create: _c,
	}
}

// InviteBindingUpsertBulk is the builder for "upsert"-ing
// a bulk of InviteBinding nodes.
type InviteBindingUpsertBulk struct {
	create *InviteBindingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InviteBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InviteBindingUpsertBulk) UpdateNewValues() *InviteBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invitebinding.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InviteBinding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InviteBindingUpsertBulk) Ignore() *InviteBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InviteBindingUpsertBulk) DoNothing() *InviteBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InviteBindingCreateBulk.OnConflict
// documentation for more info.
func (u *InviteBindingUpsertBulk) Update(set func(*InviteBindingUpsert)) *InviteBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InviteBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterUserID sets the "inviter_user_id" field.
func (u *InviteBindingUpsertBulk) SetInviterUserID(v int64) *InviteBindingUpsertBulk {
	return u.Update(func(s *InviteBindingUpsert) {
		s.SetInviterUserID(v)
	})
}

// UpdateInviterUserID sets the "inviter_user_id" field to the value that was provided on create.
func (u *InviteBindingUpsertBulk) UpdateInviterUserID() *InviteBindingUpsertBulk {
	return u.Update(func(s *InviteBindingUpsert) {
		s.UpdateInviterUserID()
	})
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (u *InviteBindingUpsertBulk) SetInviteeUserID(v int64) *InviteBindingUpsertBulk {
	return u.Update(func(s *InviteBindingUpsert) {
		s.SetInviteeUserID(v)
	})
}

// UpdateInviteeUserID sets the "invitee_user_id" field to the value that was provided on create.
func (u *InviteBindingUpsertBulk) UpdateInviteeUserID() *InviteBindingUpsertBulk {
	return u.Update(func(s *InviteBindingUpsert) {
		s.UpdateInviteeUserID()
	})
}

// SetInviteCodeID sets the "invite_code_id" field.
func (u *InviteBindingUpsertBulk) SetInviteCodeID(v int64) *InviteBindingUpsertBulk {
	return u.Update(func(s *InviteBindingUpsert) {
		s.SetInviteCodeID(v)
	})
}

// UpdateInviteCodeID sets the "invite_code_id" field to the value that was provided on create.
func (u *InviteBindingUpsertBulk) UpdateInviteCodeID() *InviteBindingUpsertBulk {
	return u.Update(func(s *InviteBindingUpsert) {
		s.UpdateInviteCodeID()
	})
}

// Exec executes the query.
func (u *InviteBindingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InviteBindingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InviteBindingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InviteBindingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
