// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/invoicerequest"
)

// InvoiceRequest is the model entity for the InvoiceRequest schema.
type InvoiceRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// TaxID holds the value of the "tax_id" field.
	TaxID string `json:"tax_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Remarks holds the value of the "remarks" field.
	Remarks string `json:"remarks,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// BaseAmount holds the value of the "base_amount" field.
	BaseAmount float64 `json:"base_amount,omitempty"`
	// ServiceFee holds the value of the "service_fee" field.
	ServiceFee float64 `json:"service_fee,omitempty"`
	// TotalAmount holds the value of the "total_amount" field.
	TotalAmount float64 `json:"total_amount,omitempty"`
	// NetAmount holds the value of the "net_amount" field.
	NetAmount float64 `json:"net_amount,omitempty"`
	// TaxAmount holds the value of the "tax_amount" field.
	TaxAmount float64 `json:"tax_amount,omitempty"`
	// ItemName holds the value of the "item_name" field.
	ItemName string `json:"item_name,omitempty"`
	// TaxRate holds the value of the "tax_rate" field.
	TaxRate float64 `json:"tax_rate,omitempty"`
	// FeeType holds the value of the "fee_type" field.
	FeeType string `json:"fee_type,omitempty"`
	// FeeValue holds the value of the "fee_value" field.
	FeeValue float64 `json:"fee_value,omitempty"`
	// FeeUpperAmount holds the value of the "fee_upper_amount" field.
	FeeUpperAmount *float64 `json:"fee_upper_amount,omitempty"`
	// OperationKey holds the value of the "operation_key" field.
	OperationKey string `json:"operation_key,omitempty"`
	// Fingerprint holds the value of the "fingerprint" field.
	Fingerprint string `json:"fingerprint,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt *time.Time `json:"submitted_at,omitempty"`
	// IssuedAt holds the value of the "issued_at" field.
	IssuedAt *time.Time `json:"issued_at,omitempty"`
	// IssuedBy holds the value of the "issued_by" field.
	IssuedBy *int64 `json:"issued_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvoiceRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoicerequest.FieldBaseAmount, invoicerequest.FieldServiceFee, invoicerequest.FieldTotalAmount, invoicerequest.FieldNetAmount, invoicerequest.FieldTaxAmount, invoicerequest.FieldTaxRate, invoicerequest.FieldFeeValue, invoicerequest.FieldFeeUpperAmount:
			values[i] = new(sql.NullFloat64)
		case invoicerequest.FieldID, invoicerequest.FieldUserID, invoicerequest.FieldIssuedBy:
			values[i] = new(sql.NullInt64)
		case invoicerequest.FieldStatus, invoicerequest.FieldTaxID, invoicerequest.FieldTitle, invoicerequest.FieldEmail, invoicerequest.FieldRemarks, invoicerequest.FieldCurrency, invoicerequest.FieldItemName, invoicerequest.FieldFeeType, invoicerequest.FieldOperationKey, invoicerequest.FieldFingerprint:
			values[i] = new(sql.NullString)
		case invoicerequest.FieldExpiresAt, invoicerequest.FieldSubmittedAt, invoicerequest.FieldIssuedAt, invoicerequest.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvoiceRequest fields.
func (_m *InvoiceRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoicerequest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invoicerequest.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case invoicerequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case invoicerequest.FieldTaxID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_id", values[i])
			} else if value.Valid {
				_m.TaxID = value.String
			}
		case invoicerequest.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case invoicerequest.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case invoicerequest.FieldRemarks:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remarks", values[i])
			} else if value.Valid {
				_m.Remarks = value.String
			}
		case invoicerequest.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case invoicerequest.FieldBaseAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field base_amount", values[i])
			} else if value.Valid {
				_m.BaseAmount = value.Float64
			}
		case invoicerequest.FieldServiceFee:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field service_fee", values[i])
			} else if value.Valid {
				_m.ServiceFee = value.Float64
			}
		case invoicerequest.FieldTotalAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_amount", values[i])
			} else if value.Valid {
				_m.TotalAmount = value.Float64
			}
		case invoicerequest.FieldNetAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field net_amount", values[i])
			} else if value.Valid {
				_m.NetAmount = value.Float64
			}
		case invoicerequest.FieldTaxAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field tax_amount", values[i])
			} else if value.Valid {
				_m.TaxAmount = value.Float64
			}
		case invoicerequest.FieldItemName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field item_name", values[i])
			} else if value.Valid {
				_m.ItemName = value.String
			}
		case invoicerequest.FieldTaxRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field tax_rate", values[i])
			} else if value.Valid {
				_m.TaxRate = value.Float64
			}
		case invoicerequest.FieldFeeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fee_type", values[i])
			} else if value.Valid {
				_m.FeeType = value.String
			}
		case invoicerequest.FieldFeeValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fee_value", values[i])
			} else if value.Valid {
				_m.FeeValue = value.Float64
			}
		case invoicerequest.FieldFeeUpperAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fee_upper_amount", values[i])
			} else if value.Valid {
				_m.FeeUpperAmount = new(float64)
				*_m.FeeUpperAmount = value.Float64
			}
		case invoicerequest.FieldOperationKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation_key", values[i])
			} else if value.Valid {
				_m.OperationKey = value.String
			}
		case invoicerequest.FieldFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fingerprint", values[i])
			} else if value.Valid {
				_m.Fingerprint = value.String
			}
		case invoicerequest.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case invoicerequest.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				_m.SubmittedAt = new(time.Time)
				*_m.SubmittedAt = value.Time
			}
		case invoicerequest.FieldIssuedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field issued_at", values[i])
			} else if value.Valid {
				_m.IssuedAt = new(time.Time)
				*_m.IssuedAt = value.Time
			}
		case invoicerequest.FieldIssuedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field issued_by", values[i])
			} else if value.Valid {
				_m.IssuedBy = new(int64)
				*_m.IssuedBy = value.Int64
			}
		case invoicerequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvoiceRequest.
// This includes values selected through modifiers, order, etc.
func (_m *InvoiceRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this InvoiceRequest.
// Note that you need to call InvoiceRequest.Unwrap() before calling this method if this InvoiceRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvoiceRequest) Update() *InvoiceRequestUpdateOne {
	return NewInvoiceRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvoiceRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvoiceRequest) Unwrap() *InvoiceRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvoiceRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvoiceRequest) String() string {
	var builder strings.Builder
	builder.WriteString("InvoiceRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("tax_id=")
	builder.WriteString(_m.TaxID)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("remarks=")
	builder.WriteString(_m.Remarks)
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("base_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.BaseAmount))
	builder.WriteString(", ")
	builder.WriteString("service_fee=")
	builder.WriteString(fmt.Sprintf("%v", _m.ServiceFee))
	builder.WriteString(", ")
	builder.WriteString("total_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalAmount))
	builder.WriteString(", ")
	builder.WriteString("net_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.NetAmount))
	builder.WriteString(", ")
	builder.WriteString("tax_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaxAmount))
	builder.WriteString(", ")
	builder.WriteString("item_name=")
	builder.WriteString(_m.ItemName)
	builder.WriteString(", ")
	builder.WriteString("tax_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaxRate))
	builder.WriteString(", ")
	builder.WriteString("fee_type=")
	builder.WriteString(_m.FeeType)
	builder.WriteString(", ")
	builder.WriteString("fee_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeeValue))
	builder.WriteString(", ")
	if v := _m.FeeUpperAmount; v != nil {
		builder.WriteString("fee_upper_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("operation_key=")
	builder.WriteString(_m.OperationKey)
	builder.WriteString(", ")
	builder.WriteString("fingerprint=")
	builder.WriteString(_m.Fingerprint)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.SubmittedAt; v != nil {
		builder.WriteString("submitted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.IssuedAt; v != nil {
		builder.WriteString("issued_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.IssuedBy; v != nil {
		builder.WriteString("issued_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InvoiceRequests is a parsable slice of InvoiceRequest.
type InvoiceRequests []*InvoiceRequest
