// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoicerequest"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// InvoiceRequestUpdate is the builder for updating InvoiceRequest entities.
type InvoiceRequestUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceRequestMutation
}

// Where appends a list predicates to the InvoiceRequestUpdate builder.
func (_u *InvoiceRequestUpdate) Where(ps ...predicate.InvoiceRequest) *InvoiceRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceRequestUpdate) SetStatus(v string) *InvoiceRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableStatus(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTaxID sets the "tax_id" field.
func (_u *InvoiceRequestUpdate) SetTaxID(v string) *InvoiceRequestUpdate {
	_u.mutation.SetTaxID(v)
	return _u
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableTaxID(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetTaxID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *InvoiceRequestUpdate) SetTitle(v string) *InvoiceRequestUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableTitle(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *InvoiceRequestUpdate) SetEmail(v string) *InvoiceRequestUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableEmail(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetRemarks sets the "remarks" field.
func (_u *InvoiceRequestUpdate) SetRemarks(v string) *InvoiceRequestUpdate {
	_u.mutation.SetRemarks(v)
	return _u
}

// SetNillableRemarks sets the "remarks" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableRemarks(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetRemarks(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *InvoiceRequestUpdate) SetCurrency(v string) *InvoiceRequestUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableCurrency(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetBaseAmount sets the "base_amount" field.
func (_u *InvoiceRequestUpdate) SetBaseAmount(v float64) *InvoiceRequestUpdate {
	_u.mutation.ResetBaseAmount()
	_u.mutation.SetBaseAmount(v)
	return _u
}

// SetNillableBaseAmount sets the "base_amount" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableBaseAmount(v *float64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetBaseAmount(*v)
	}
	return _u
}

// AddBaseAmount adds value to the "base_amount" field.
func (_u *InvoiceRequestUpdate) AddBaseAmount(v float64) *InvoiceRequestUpdate {
	_u.mutation.AddBaseAmount(v)
	return _u
}

// SetServiceFee sets the "service_fee" field.
func (_u *InvoiceRequestUpdate) SetServiceFee(v float64) *InvoiceRequestUpdate {
	_u.mutation.ResetServiceFee()
	_u.mutation.SetServiceFee(v)
	return _u
}

// SetNillableServiceFee sets the "service_fee" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableServiceFee(v *float64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetServiceFee(*v)
	}
	return _u
}

// AddServiceFee adds value to the "service_fee" field.
func (_u *InvoiceRequestUpdate) AddServiceFee(v float64) *InvoiceRequestUpdate {
	_u.mutation.AddServiceFee(v)
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *InvoiceRequestUpdate) SetTotalAmount(v float64) *InvoiceRequestUpdate {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableTotalAmount(v *float64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *InvoiceRequestUpdate) AddTotalAmount(v float64) *InvoiceRequestUpdate {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetNetAmount sets the "net_amount" field.
func (_u *InvoiceRequestUpdate) SetNetAmount(v float64) *InvoiceRequestUpdate {
	_u.mutation.ResetNetAmount()
	_u.mutation.SetNetAmount(v)
	return _u
}

// SetNillableNetAmount sets the "net_amount" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableNetAmount(v *float64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetNetAmount(*v)
	}
	return _u
}

// AddNetAmount adds value to the "net_amount" field.
func (_u *InvoiceRequestUpdate) AddNetAmount(v float64) *InvoiceRequestUpdate {
	_u.mutation.AddNetAmount(v)
	return _u
}

// SetTaxAmount sets the "tax_amount" field.
func (_u *InvoiceRequestUpdate) SetTaxAmount(v float64) *InvoiceRequestUpdate {
	_u.mutation.ResetTaxAmount()
	_u.mutation.SetTaxAmount(v)
	return _u
}

// SetNillableTaxAmount sets the "tax_amount" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableTaxAmount(v *float64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetTaxAmount(*v)
	}
	return _u
}

// AddTaxAmount adds value to the "tax_amount" field.
func (_u *InvoiceRequestUpdate) AddTaxAmount(v float64) *InvoiceRequestUpdate {
	_u.mutation.AddTaxAmount(v)
	return _u
}

// SetItemName sets the "item_name" field.
func (_u *InvoiceRequestUpdate) SetItemName(v string) *InvoiceRequestUpdate {
	_u.mutation.SetItemName(v)
	return _u
}

// SetNillableItemName sets the "item_name" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableItemName(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetItemName(*v)
	}
	return _u
}

// SetTaxRate sets the "tax_rate" field.
func (_u *InvoiceRequestUpdate) SetTaxRate(v float64) *InvoiceRequestUpdate {
	_u.mutation.ResetTaxRate()
	_u.mutation.SetTaxRate(v)
	return _u
}

// SetNillableTaxRate sets the "tax_rate" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableTaxRate(v *float64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetTaxRate(*v)
	}
	return _u
}

// AddTaxRate adds value to the "tax_rate" field.
func (_u *InvoiceRequestUpdate) AddTaxRate(v float64) *InvoiceRequestUpdate {
	_u.mutation.AddTaxRate(v)
	return _u
}

// SetFeeType sets the "fee_type" field.
func (_u *InvoiceRequestUpdate) SetFeeType(v string) *InvoiceRequestUpdate {
	_u.mutation.SetFeeType(v)
	return _u
}

// SetNillableFeeType sets the "fee_type" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableFeeType(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetFeeType(*v)
	}
	return _u
}

// SetFeeValue sets the "fee_value" field.
func (_u *InvoiceRequestUpdate) SetFeeValue(v float64) *InvoiceRequestUpdate {
	_u.mutation.ResetFeeValue()
	_u.mutation.SetFeeValue(v)
	return _u
}

// SetNillableFeeValue sets the "fee_value" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableFeeValue(v *float64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetFeeValue(*v)
	}
	return _u
}

// AddFeeValue adds value to the "fee_value" field.
func (_u *InvoiceRequestUpdate) AddFeeValue(v float64) *InvoiceRequestUpdate {
	_u.mutation.AddFeeValue(v)
	return _u
}

// SetFeeUpperAmount sets the "fee_upper_amount" field.
func (_u *InvoiceRequestUpdate) SetFeeUpperAmount(v float64) *InvoiceRequestUpdate {
	_u.mutation.ResetFeeUpperAmount()
	_u.mutation.SetFeeUpperAmount(v)
	return _u
}

// SetNillableFeeUpperAmount sets the "fee_upper_amount" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableFeeUpperAmount(v *float64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetFeeUpperAmount(*v)
	}
	return _u
}

// AddFeeUpperAmount adds value to the "fee_upper_amount" field.
func (_u *InvoiceRequestUpdate) AddFeeUpperAmount(v float64) *InvoiceRequestUpdate {
	_u.mutation.AddFeeUpperAmount(v)
	return _u
}

// ClearFeeUpperAmount clears the value of the "fee_upper_amount" field.
func (_u *InvoiceRequestUpdate) ClearFeeUpperAmount() *InvoiceRequestUpdate {
	_u.mutation.ClearFeeUpperAmount()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *InvoiceRequestUpdate) SetExpiresAt(v time.Time) *InvoiceRequestUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableExpiresAt(v *time.Time) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *InvoiceRequestUpdate) SetSubmittedAt(v time.Time) *InvoiceRequestUpdate {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableSubmittedAt(v *time.Time) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (_u *InvoiceRequestUpdate) ClearSubmittedAt() *InvoiceRequestUpdate {
	_u.mutation.ClearSubmittedAt()
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *InvoiceRequestUpdate) SetIssuedAt(v time.Time) *InvoiceRequestUpdate {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableIssuedAt(v *time.Time) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *InvoiceRequestUpdate) ClearIssuedAt() *InvoiceRequestUpdate {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetIssuedBy sets the "issued_by" field.
func (_u *InvoiceRequestUpdate) SetIssuedBy(v int64) *InvoiceRequestUpdate {
	_u.mutation.ResetIssuedBy()
	_u.mutation.SetIssuedBy(v)
	return _u
}

// SetNillableIssuedBy sets the "issued_by" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableIssuedBy(v *int64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetIssuedBy(*v)
	}
	return _u
}

// AddIssuedBy adds value to the "issued_by" field.
func (_u *InvoiceRequestUpdate) AddIssuedBy(v int64) *InvoiceRequestUpdate {
	_u.mutation.AddIssuedBy(v)
	return _u
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (_u *InvoiceRequestUpdate) ClearIssuedBy() *InvoiceRequestUpdate {
	_u.mutation.ClearIssuedBy()
	return _u
}

// Mutation returns the InvoiceRequestMutation object of the builder.
func (_u *InvoiceRequestUpdate) Mutation() *InvoiceRequestMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceRequestUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceRequestUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := invoicerequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxID(); ok {
		if err := invoicerequest.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.tax_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := invoicerequest.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := invoicerequest.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remarks(); ok {
		if err := invoicerequest.RemarksValidator(v); err != nil {
			return &ValidationError{Name: "remarks", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.remarks": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := invoicerequest.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ItemName(); ok {
		if err := invoicerequest.ItemNameValidator(v); err != nil {
			return &ValidationError{Name: "item_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.item_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FeeType(); ok {
		if err := invoicerequest.FeeTypeValidator(v); err != nil {
			return &ValidationError{Name: "fee_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.fee_type": %w`, err)}
		}
	}
	return nil
}

func (_u *InvoiceRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoicerequest.Table, invoicerequest.Columns, sqlgraph.NewFieldSpec(invoicerequest.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoicerequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxID(); ok {
		_spec.SetField(invoicerequest.FieldTaxID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(invoicerequest.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(invoicerequest.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Remarks(); ok {
		_spec.SetField(invoicerequest.FieldRemarks, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(invoicerequest.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseAmount(); ok {
		_spec.SetField(invoicerequest.FieldBaseAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseAmount(); ok {
		_spec.AddField(invoicerequest.FieldBaseAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ServiceFee(); ok {
		_spec.SetField(invoicerequest.FieldServiceFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedServiceFee(); ok {
		_spec.AddField(invoicerequest.FieldServiceFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(invoicerequest.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(invoicerequest.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.NetAmount(); ok {
		_spec.SetField(invoicerequest.FieldNetAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedNetAmount(); ok {
		_spec.AddField(invoicerequest.FieldNetAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TaxAmount(); ok {
		_spec.SetField(invoicerequest.FieldTaxAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTaxAmount(); ok {
		_spec.AddField(invoicerequest.FieldTaxAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ItemName(); ok {
		_spec.SetField(invoicerequest.FieldItemName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxRate(); ok {
		_spec.SetField(invoicerequest.FieldTaxRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTaxRate(); ok {
		_spec.AddField(invoicerequest.FieldTaxRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeType(); ok {
		_spec.SetField(invoicerequest.FieldFeeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FeeValue(); ok {
		_spec.SetField(invoicerequest.FieldFeeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeValue(); ok {
		_spec.AddField(invoicerequest.FieldFeeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeUpperAmount(); ok {
		_spec.SetField(invoicerequest.FieldFeeUpperAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeUpperAmount(); ok {
		_spec.AddField(invoicerequest.FieldFeeUpperAmount, field.TypeFloat64, value)
	}
	if _u.mutation.FeeUpperAmountCleared() {
		_spec.ClearField(invoicerequest.FieldFeeUpperAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(invoicerequest.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(invoicerequest.FieldSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.SubmittedAtCleared() {
		_spec.ClearField(invoicerequest.FieldSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(invoicerequest.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(invoicerequest.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IssuedBy(); ok {
		_spec.SetField(invoicerequest.FieldIssuedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedIssuedBy(); ok {
		_spec.AddField(invoicerequest.FieldIssuedBy, field.TypeInt64, value)
	}
	if _u.mutation.IssuedByCleared() {
		_spec.ClearField(invoicerequest.FieldIssuedBy, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoicerequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceRequestUpdateOne is the builder for updating a single InvoiceRequest entity.
type InvoiceRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceRequestMutation
}

// SetStatus sets the "status" field.
func (_u *InvoiceRequestUpdateOne) SetStatus(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableStatus(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTaxID sets the "tax_id" field.
func (_u *InvoiceRequestUpdateOne) SetTaxID(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetTaxID(v)
	return _u
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableTaxID(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetTaxID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *InvoiceRequestUpdateOne) SetTitle(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableTitle(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *InvoiceRequestUpdateOne) SetEmail(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableEmail(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetRemarks sets the "remarks" field.
func (_u *InvoiceRequestUpdateOne) SetRemarks(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetRemarks(v)
	return _u
}

// SetNillableRemarks sets the "remarks" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableRemarks(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetRemarks(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *InvoiceRequestUpdateOne) SetCurrency(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableCurrency(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetBaseAmount sets the "base_amount" field.
func (_u *InvoiceRequestUpdateOne) SetBaseAmount(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.ResetBaseAmount()
	_u.mutation.SetBaseAmount(v)
	return _u
}

// SetNillableBaseAmount sets the "base_amount" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableBaseAmount(v *float64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetBaseAmount(*v)
	}
	return _u
}

// AddBaseAmount adds value to the "base_amount" field.
func (_u *InvoiceRequestUpdateOne) AddBaseAmount(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.AddBaseAmount(v)
	return _u
}

// SetServiceFee sets the "service_fee" field.
func (_u *InvoiceRequestUpdateOne) SetServiceFee(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.ResetServiceFee()
	_u.mutation.SetServiceFee(v)
	return _u
}

// SetNillableServiceFee sets the "service_fee" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableServiceFee(v *float64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetServiceFee(*v)
	}
	return _u
}

// AddServiceFee adds value to the "service_fee" field.
func (_u *InvoiceRequestUpdateOne) AddServiceFee(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.AddServiceFee(v)
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *InvoiceRequestUpdateOne) SetTotalAmount(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableTotalAmount(v *float64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *InvoiceRequestUpdateOne) AddTotalAmount(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetNetAmount sets the "net_amount" field.
func (_u *InvoiceRequestUpdateOne) SetNetAmount(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.ResetNetAmount()
	_u.mutation.SetNetAmount(v)
	return _u
}

// SetNillableNetAmount sets the "net_amount" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableNetAmount(v *float64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetNetAmount(*v)
	}
	return _u
}

// AddNetAmount adds value to the "net_amount" field.
func (_u *InvoiceRequestUpdateOne) AddNetAmount(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.AddNetAmount(v)
	return _u
}

// SetTaxAmount sets the "tax_amount" field.
func (_u *InvoiceRequestUpdateOne) SetTaxAmount(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.ResetTaxAmount()
	_u.mutation.SetTaxAmount(v)
	return _u
}

// SetNillableTaxAmount sets the "tax_amount" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableTaxAmount(v *float64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetTaxAmount(*v)
	}
	return _u
}

// AddTaxAmount adds value to the "tax_amount" field.
func (_u *InvoiceRequestUpdateOne) AddTaxAmount(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.AddTaxAmount(v)
	return _u
}

// SetItemName sets the "item_name" field.
func (_u *InvoiceRequestUpdateOne) SetItemName(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetItemName(v)
	return _u
}

// SetNillableItemName sets the "item_name" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableItemName(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetItemName(*v)
	}
	return _u
}

// SetTaxRate sets the "tax_rate" field.
func (_u *InvoiceRequestUpdateOne) SetTaxRate(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.ResetTaxRate()
	_u.mutation.SetTaxRate(v)
	return _u
}

// SetNillableTaxRate sets the "tax_rate" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableTaxRate(v *float64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetTaxRate(*v)
	}
	return _u
}

// AddTaxRate adds value to the "tax_rate" field.
func (_u *InvoiceRequestUpdateOne) AddTaxRate(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.AddTaxRate(v)
	return _u
}

// SetFeeType sets the "fee_type" field.
func (_u *InvoiceRequestUpdateOne) SetFeeType(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetFeeType(v)
	return _u
}

// SetNillableFeeType sets the "fee_type" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableFeeType(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetFeeType(*v)
	}
	return _u
}

// SetFeeValue sets the "fee_value" field.
func (_u *InvoiceRequestUpdateOne) SetFeeValue(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.ResetFeeValue()
	_u.mutation.SetFeeValue(v)
	return _u
}

// SetNillableFeeValue sets the "fee_value" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableFeeValue(v *float64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetFeeValue(*v)
	}
	return _u
}

// AddFeeValue adds value to the "fee_value" field.
func (_u *InvoiceRequestUpdateOne) AddFeeValue(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.AddFeeValue(v)
	return _u
}

// SetFeeUpperAmount sets the "fee_upper_amount" field.
func (_u *InvoiceRequestUpdateOne) SetFeeUpperAmount(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.ResetFeeUpperAmount()
	_u.mutation.SetFeeUpperAmount(v)
	return _u
}

// SetNillableFeeUpperAmount sets the "fee_upper_amount" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableFeeUpperAmount(v *float64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetFeeUpperAmount(*v)
	}
	return _u
}

// AddFeeUpperAmount adds value to the "fee_upper_amount" field.
func (_u *InvoiceRequestUpdateOne) AddFeeUpperAmount(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.AddFeeUpperAmount(v)
	return _u
}

// ClearFeeUpperAmount clears the value of the "fee_upper_amount" field.
func (_u *InvoiceRequestUpdateOne) ClearFeeUpperAmount() *InvoiceRequestUpdateOne {
	_u.mutation.ClearFeeUpperAmount()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *InvoiceRequestUpdateOne) SetExpiresAt(v time.Time) *InvoiceRequestUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableExpiresAt(v *time.Time) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *InvoiceRequestUpdateOne) SetSubmittedAt(v time.Time) *InvoiceRequestUpdateOne {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableSubmittedAt(v *time.Time) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (_u *InvoiceRequestUpdateOne) ClearSubmittedAt() *InvoiceRequestUpdateOne {
	_u.mutation.ClearSubmittedAt()
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *InvoiceRequestUpdateOne) SetIssuedAt(v time.Time) *InvoiceRequestUpdateOne {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableIssuedAt(v *time.Time) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *InvoiceRequestUpdateOne) ClearIssuedAt() *InvoiceRequestUpdateOne {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetIssuedBy sets the "issued_by" field.
func (_u *InvoiceRequestUpdateOne) SetIssuedBy(v int64) *InvoiceRequestUpdateOne {
	_u.mutation.ResetIssuedBy()
	_u.mutation.SetIssuedBy(v)
	return _u
}

// SetNillableIssuedBy sets the "issued_by" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableIssuedBy(v *int64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetIssuedBy(*v)
	}
	return _u
}

// AddIssuedBy adds value to the "issued_by" field.
func (_u *InvoiceRequestUpdateOne) AddIssuedBy(v int64) *InvoiceRequestUpdateOne {
	_u.mutation.AddIssuedBy(v)
	return _u
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (_u *InvoiceRequestUpdateOne) ClearIssuedBy() *InvoiceRequestUpdateOne {
	_u.mutation.ClearIssuedBy()
	return _u
}

// Mutation returns the InvoiceRequestMutation object of the builder.
func (_u *InvoiceRequestUpdateOne) Mutation() *InvoiceRequestMutation {
	return _u.mutation
}

// Where appends a list predicates to the InvoiceRequestUpdate builder.
func (_u *InvoiceRequestUpdateOne) Where(ps ...predicate.InvoiceRequest) *InvoiceRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceRequestUpdateOne) Select(field string, fields ...string) *InvoiceRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvoiceRequest entity.
func (_u *InvoiceRequestUpdateOne) Save(ctx context.Context) (*InvoiceRequest, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceRequestUpdateOne) SaveX(ctx context.Context) *InvoiceRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceRequestUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := invoicerequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxID(); ok {
		if err := invoicerequest.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.tax_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := invoicerequest.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := invoicerequest.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remarks(); ok {
		if err := invoicerequest.RemarksValidator(v); err != nil {
			return &ValidationError{Name: "remarks", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.remarks": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := invoicerequest.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ItemName(); ok {
		if err := invoicerequest.ItemNameValidator(v); err != nil {
			return &ValidationError{Name: "item_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.item_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FeeType(); ok {
		if err := invoicerequest.FeeTypeValidator(v); err != nil {
			return &ValidationError{Name: "fee_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.fee_type": %w`, err)}
		}
	}
	return nil
}

func (_u *InvoiceRequestUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoicerequest.Table, invoicerequest.Columns, sqlgraph.NewFieldSpec(invoicerequest.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoicerequest.FieldID)
		for _, f := range fields {
			if !invoicerequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoicerequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoicerequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxID(); ok {
		_spec.SetField(invoicerequest.FieldTaxID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(invoicerequest.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(invoicerequest.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Remarks(); ok {
		_spec.SetField(invoicerequest.FieldRemarks, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(invoicerequest.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseAmount(); ok {
		_spec.SetField(invoicerequest.FieldBaseAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseAmount(); ok {
		_spec.AddField(invoicerequest.FieldBaseAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ServiceFee(); ok {
		_spec.SetField(invoicerequest.FieldServiceFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedServiceFee(); ok {
		_spec.AddField(invoicerequest.FieldServiceFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(invoicerequest.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(invoicerequest.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.NetAmount(); ok {
		_spec.SetField(invoicerequest.FieldNetAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedNetAmount(); ok {
		_spec.AddField(invoicerequest.FieldNetAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TaxAmount(); ok {
		_spec.SetField(invoicerequest.FieldTaxAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTaxAmount(); ok {
		_spec.AddField(invoicerequest.FieldTaxAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ItemName(); ok {
		_spec.SetField(invoicerequest.FieldItemName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxRate(); ok {
		_spec.SetField(invoicerequest.FieldTaxRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTaxRate(); ok {
		_spec.AddField(invoicerequest.FieldTaxRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeType(); ok {
		_spec.SetField(invoicerequest.FieldFeeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FeeValue(); ok {
		_spec.SetField(invoicerequest.FieldFeeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeValue(); ok {
		_spec.AddField(invoicerequest.FieldFeeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeUpperAmount(); ok {
		_spec.SetField(invoicerequest.FieldFeeUpperAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeUpperAmount(); ok {
		_spec.AddField(invoicerequest.FieldFeeUpperAmount, field.TypeFloat64, value)
	}
	if _u.mutation.FeeUpperAmountCleared() {
		_spec.ClearField(invoicerequest.FieldFeeUpperAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(invoicerequest.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(invoicerequest.FieldSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.SubmittedAtCleared() {
		_spec.ClearField(invoicerequest.FieldSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(invoicerequest.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(invoicerequest.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IssuedBy(); ok {
		_spec.SetField(invoicerequest.FieldIssuedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedIssuedBy(); ok {
		_spec.AddField(invoicerequest.FieldIssuedBy, field.TypeInt64, value)
	}
	if _u.mutation.IssuedByCleared() {
		_spec.ClearField(invoicerequest.FieldIssuedBy, field.TypeInt64)
	}
	_node = &InvoiceRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoicerequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
