// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoicerequest"
)

// InvoiceRequestCreate is the builder for creating a InvoiceRequest entity.
type InvoiceRequestCreate struct {
	config
	mutation *InvoiceRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *InvoiceRequestCreate) SetUserID(v int64) *InvoiceRequestCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *InvoiceRequestCreate) SetStatus(v string) *InvoiceRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableStatus(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTaxID sets the "tax_id" field.
func (_c *InvoiceRequestCreate) SetTaxID(v string) *InvoiceRequestCreate {
	_c.mutation.SetTaxID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *InvoiceRequestCreate) SetTitle(v string) *InvoiceRequestCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *InvoiceRequestCreate) SetEmail(v string) *InvoiceRequestCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetRemarks sets the "remarks" field.
func (_c *InvoiceRequestCreate) SetRemarks(v string) *InvoiceRequestCreate {
	_c.mutation.SetRemarks(v)
	return _c
}

// SetNillableRemarks sets the "remarks" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableRemarks(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetRemarks(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *InvoiceRequestCreate) SetCurrency(v string) *InvoiceRequestCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableCurrency(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetBaseAmount sets the "base_amount" field.
func (_c *InvoiceRequestCreate) SetBaseAmount(v float64) *InvoiceRequestCreate {
	_c.mutation.SetBaseAmount(v)
	return _c
}

// SetServiceFee sets the "service_fee" field.
func (_c *InvoiceRequestCreate) SetServiceFee(v float64) *InvoiceRequestCreate {
	_c.mutation.SetServiceFee(v)
	return _c
}

// SetTotalAmount sets the "total_amount" field.
func (_c *InvoiceRequestCreate) SetTotalAmount(v float64) *InvoiceRequestCreate {
	_c.mutation.SetTotalAmount(v)
	return _c
}

// SetNetAmount sets the "net_amount" field.
func (_c *InvoiceRequestCreate) SetNetAmount(v float64) *InvoiceRequestCreate {
	_c.mutation.SetNetAmount(v)
	return _c
}

// SetTaxAmount sets the "tax_amount" field.
func (_c *InvoiceRequestCreate) SetTaxAmount(v float64) *InvoiceRequestCreate {
	_c.mutation.SetTaxAmount(v)
	return _c
}

// SetItemName sets the "item_name" field.
func (_c *InvoiceRequestCreate) SetItemName(v string) *InvoiceRequestCreate {
	_c.mutation.SetItemName(v)
	return _c
}

// SetTaxRate sets the "tax_rate" field.
func (_c *InvoiceRequestCreate) SetTaxRate(v float64) *InvoiceRequestCreate {
	_c.mutation.SetTaxRate(v)
	return _c
}

// SetFeeType sets the "fee_type" field.
func (_c *InvoiceRequestCreate) SetFeeType(v string) *InvoiceRequestCreate {
	_c.mutation.SetFeeType(v)
	return _c
}

// SetFeeValue sets the "fee_value" field.
func (_c *InvoiceRequestCreate) SetFeeValue(v float64) *InvoiceRequestCreate {
	_c.mutation.SetFeeValue(v)
	return _c
}

// SetFeeUpperAmount sets the "fee_upper_amount" field.
func (_c *InvoiceRequestCreate) SetFeeUpperAmount(v float64) *InvoiceRequestCreate {
	_c.mutation.SetFeeUpperAmount(v)
	return _c
}

// SetNillableFeeUpperAmount sets the "fee_upper_amount" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableFeeUpperAmount(v *float64) *InvoiceRequestCreate {
	if v != nil {
		_c.SetFeeUpperAmount(*v)
	}
	return _c
}

// SetOperationKey sets the "operation_key" field.
func (_c *InvoiceRequestCreate) SetOperationKey(v string) *InvoiceRequestCreate {
	_c.mutation.SetOperationKey(v)
	return _c
}

// SetFingerprint sets the "fingerprint" field.
func (_c *InvoiceRequestCreate) SetFingerprint(v string) *InvoiceRequestCreate {
	_c.mutation.SetFingerprint(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *InvoiceRequestCreate) SetExpiresAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetSubmittedAt sets the "submitted_at" field.
func (_c *InvoiceRequestCreate) SetSubmittedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetSubmittedAt(v)
	return _c
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableSubmittedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetSubmittedAt(*v)
	}
	return _c
}

// SetIssuedAt sets the "issued_at" field.
func (_c *InvoiceRequestCreate) SetIssuedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetIssuedAt(v)
	return _c
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableIssuedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetIssuedAt(*v)
	}
	return _c
}

// SetIssuedBy sets the "issued_by" field.
func (_c *InvoiceRequestCreate) SetIssuedBy(v int64) *InvoiceRequestCreate {
	_c.mutation.SetIssuedBy(v)
	return _c
}

// SetNillableIssuedBy sets the "issued_by" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableIssuedBy(v *int64) *InvoiceRequestCreate {
	if v != nil {
		_c.SetIssuedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceRequestCreate) SetCreatedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableCreatedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the InvoiceRequestMutation object of the builder.
func (_c *InvoiceRequestCreate) Mutation() *InvoiceRequestMutation {
	return _c.mutation
}

// Save creates the InvoiceRequest in the database.
func (_c *InvoiceRequestCreate) Save(ctx context.Context) (*InvoiceRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceRequestCreate) SaveX(ctx context.Context) *InvoiceRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceRequestCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := invoicerequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Remarks(); !ok {
		v := invoicerequest.DefaultRemarks
		_c.mutation.SetRemarks(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := invoicerequest.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoicerequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceRequestCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InvoiceRequest.user_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "InvoiceRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := invoicerequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaxID(); !ok {
		return &ValidationError{Name: "tax_id", err: errors.New(`ent: missing required field "InvoiceRequest.tax_id"`)}
	}
	if v, ok := _c.mutation.TaxID(); ok {
		if err := invoicerequest.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.tax_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "InvoiceRequest.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := invoicerequest.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "InvoiceRequest.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := invoicerequest.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Remarks(); !ok {
		return &ValidationError{Name: "remarks", err: errors.New(`ent: missing required field "InvoiceRequest.remarks"`)}
	}
	if v, ok := _c.mutation.Remarks(); ok {
		if err := invoicerequest.RemarksValidator(v); err != nil {
			return &ValidationError{Name: "remarks", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.remarks": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "InvoiceRequest.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := invoicerequest.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseAmount(); !ok {
		return &ValidationError{Name: "base_amount", err: errors.New(`ent: missing required field "InvoiceRequest.base_amount"`)}
	}
	if _, ok := _c.mutation.ServiceFee(); !ok {
		return &ValidationError{Name: "service_fee", err: errors.New(`ent: missing required field "InvoiceRequest.service_fee"`)}
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		return &ValidationError{Name: "total_amount", err: errors.New(`ent: missing required field "InvoiceRequest.total_amount"`)}
	}
	if _, ok := _c.mutation.NetAmount(); !ok {
		return &ValidationError{Name: "net_amount", err: errors.New(`ent: missing required field "InvoiceRequest.net_amount"`)}
	}
	if _, ok := _c.mutation.TaxAmount(); !ok {
		return &ValidationError{Name: "tax_amount", err: errors.New(`ent: missing required field "InvoiceRequest.tax_amount"`)}
	}
	if _, ok := _c.mutation.ItemName(); !ok {
		return &ValidationError{Name: "item_name", err: errors.New(`ent: missing required field "InvoiceRequest.item_name"`)}
	}
	if v, ok := _c.mutation.ItemName(); ok {
		if err := invoicerequest.ItemNameValidator(v); err != nil {
			return &ValidationError{Name: "item_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.item_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaxRate(); !ok {
		return &ValidationError{Name: "tax_rate", err: errors.New(`ent: missing required field "InvoiceRequest.tax_rate"`)}
	}
	if _, ok := _c.mutation.FeeType(); !ok {
		return &ValidationError{Name: "fee_type", err: errors.New(`ent: missing required field "InvoiceRequest.fee_type"`)}
	}
	if v, ok := _c.mutation.FeeType(); ok {
		if err := invoicerequest.FeeTypeValidator(v); err != nil {
			return &ValidationError{Name: "fee_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.fee_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FeeValue(); !ok {
		return &ValidationError{Name: "fee_value", err: errors.New(`ent: missing required field "InvoiceRequest.fee_value"`)}
	}
	if _, ok := _c.mutation.OperationKey(); !ok {
		return &ValidationError{Name: "operation_key", err: errors.New(`ent: missing required field "InvoiceRequest.operation_key"`)}
	}
	if v, ok := _c.mutation.OperationKey(); ok {
		if err := invoicerequest.OperationKeyValidator(v); err != nil {
			return &ValidationError{Name: "operation_key", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.operation_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Fingerprint(); !ok {
		return &ValidationError{Name: "fingerprint", err: errors.New(`ent: missing required field "InvoiceRequest.fingerprint"`)}
	}
	if v, ok := _c.mutation.Fingerprint(); ok {
		if err := invoicerequest.FingerprintValidator(v); err != nil {
			return &ValidationError{Name: "fingerprint", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.fingerprint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "InvoiceRequest.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceRequest.created_at"`)}
	}
	return nil
}

func (_c *InvoiceRequestCreate) sqlSave(ctx context.Context) (*InvoiceRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceRequestCreate) createSpec() (*InvoiceRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoicerequest.Table, sqlgraph.NewFieldSpec(invoicerequest.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(invoicerequest.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invoicerequest.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TaxID(); ok {
		_spec.SetField(invoicerequest.FieldTaxID, field.TypeString, value)
		_node.TaxID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(invoicerequest.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(invoicerequest.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Remarks(); ok {
		_spec.SetField(invoicerequest.FieldRemarks, field.TypeString, value)
		_node.Remarks = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(invoicerequest.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.BaseAmount(); ok {
		_spec.SetField(invoicerequest.FieldBaseAmount, field.TypeFloat64, value)
		_node.BaseAmount = value
	}
	if value, ok := _c.mutation.ServiceFee(); ok {
		_spec.SetField(invoicerequest.FieldServiceFee, field.TypeFloat64, value)
		_node.ServiceFee = value
	}
	if value, ok := _c.mutation.TotalAmount(); ok {
		_spec.SetField(invoicerequest.FieldTotalAmount, field.TypeFloat64, value)
		_node.TotalAmount = value
	}
	if value, ok := _c.mutation.NetAmount(); ok {
		_spec.SetField(invoicerequest.FieldNetAmount, field.TypeFloat64, value)
		_node.NetAmount = value
	}
	if value, ok := _c.mutation.TaxAmount(); ok {
		_spec.SetField(invoicerequest.FieldTaxAmount, field.TypeFloat64, value)
		_node.TaxAmount = value
	}
	if value, ok := _c.mutation.ItemName(); ok {
		_spec.SetField(invoicerequest.FieldItemName, field.TypeString, value)
		_node.ItemName = value
	}
	if value, ok := _c.mutation.TaxRate(); ok {
		_spec.SetField(invoicerequest.FieldTaxRate, field.TypeFloat64, value)
		_node.TaxRate = value
	}
	if value, ok := _c.mutation.FeeType(); ok {
		_spec.SetField(invoicerequest.FieldFeeType, field.TypeString, value)
		_node.FeeType = value
	}
	if value, ok := _c.mutation.FeeValue(); ok {
		_spec.SetField(invoicerequest.FieldFeeValue, field.TypeFloat64, value)
		_node.FeeValue = value
	}
	if value, ok := _c.mutation.FeeUpperAmount(); ok {
		_spec.SetField(invoicerequest.FieldFeeUpperAmount, field.TypeFloat64, value)
		_node.FeeUpperAmount = &value
	}
	if value, ok := _c.mutation.OperationKey(); ok {
		_spec.SetField(invoicerequest.FieldOperationKey, field.TypeString, value)
		_node.OperationKey = value
	}
	if value, ok := _c.mutation.Fingerprint(); ok {
		_spec.SetField(invoicerequest.FieldFingerprint, field.TypeString, value)
		_node.Fingerprint = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(invoicerequest.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.SubmittedAt(); ok {
		_spec.SetField(invoicerequest.FieldSubmittedAt, field.TypeTime, value)
		_node.SubmittedAt = &value
	}
	if value, ok := _c.mutation.IssuedAt(); ok {
		_spec.SetField(invoicerequest.FieldIssuedAt, field.TypeTime, value)
		_node.IssuedAt = &value
	}
	if value, ok := _c.mutation.IssuedBy(); ok {
		_spec.SetField(invoicerequest.FieldIssuedBy, field.TypeInt64, value)
		_node.IssuedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoicerequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceRequest.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceRequestUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceRequestCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceRequestUpsertOne {
	_c.conflict = opts
	return &InvoiceRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceRequestCreate) OnConflictColumns(columns ...string) *InvoiceRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceRequestUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceRequestUpsertOne is the builder for "upsert"-ing
	//  one InvoiceRequest node.
	InvoiceRequestUpsertOne struct {
		create *InvoiceRequestCreate
	}

	// InvoiceRequestUpsert is the "OnConflict" setter.
	InvoiceRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsert) SetStatus(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateStatus() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldStatus)
	return u
}

// SetTaxID sets the "tax_id" field.
func (u *InvoiceRequestUpsert) SetTaxID(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldTaxID, v)
	return u
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateTaxID() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldTaxID)
	return u
}

// SetTitle sets the "title" field.
func (u *InvoiceRequestUpsert) SetTitle(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateTitle() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldTitle)
	return u
}

// SetEmail sets the "email" field.
func (u *InvoiceRequestUpsert) SetEmail(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateEmail() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldEmail)
	return u
}

// SetRemarks sets the "remarks" field.
func (u *InvoiceRequestUpsert) SetRemarks(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldRemarks, v)
	return u
}

// UpdateRemarks sets the "remarks" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateRemarks() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldRemarks)
	return u
}

// SetCurrency sets the "currency" field.
func (u *InvoiceRequestUpsert) SetCurrency(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateCurrency() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldCurrency)
	return u
}

// SetBaseAmount sets the "base_amount" field.
func (u *InvoiceRequestUpsert) SetBaseAmount(v float64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldBaseAmount, v)
	return u
}

// UpdateBaseAmount sets the "base_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateBaseAmount() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldBaseAmount)
	return u
}

// AddBaseAmount adds v to the "base_amount" field.
func (u *InvoiceRequestUpsert) AddBaseAmount(v float64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldBaseAmount, v)
	return u
}

// SetServiceFee sets the "service_fee" field.
func (u *InvoiceRequestUpsert) SetServiceFee(v float64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldServiceFee, v)
	return u
}

// UpdateServiceFee sets the "service_fee" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateServiceFee() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldServiceFee)
	return u
}

// AddServiceFee adds v to the "service_fee" field.
func (u *InvoiceRequestUpsert) AddServiceFee(v float64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldServiceFee, v)
	return u
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceRequestUpsert) SetTotalAmount(v float64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldTotalAmount, v)
	return u
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateTotalAmount() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldTotalAmount)
	return u
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *InvoiceRequestUpsert) AddTotalAmount(v float64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldTotalAmount, v)
	return u
}

// SetNetAmount sets the "net_amount" field.
func (u *InvoiceRequestUpsert) SetNetAmount(v float64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldNetAmount, v)
	return u
}

// UpdateNetAmount sets the "net_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateNetAmount() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldNetAmount)
	return u
}

// AddNetAmount adds v to the "net_amount" field.
func (u *InvoiceRequestUpsert) AddNetAmount(v float64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldNetAmount, v)
	return u
}

// SetTaxAmount sets the "tax_amount" field.
func (u *InvoiceRequestUpsert) SetTaxAmount(v float64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldTaxAmount, v)
	return u
}

// UpdateTaxAmount sets the "tax_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateTaxAmount() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldTaxAmount)
	return u
}

// AddTaxAmount adds v to the "tax_amount" field.
func (u *InvoiceRequestUpsert) AddTaxAmount(v float64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldTaxAmount, v)
	return u
}

// SetItemName sets the "item_name" field.
func (u *InvoiceRequestUpsert) SetItemName(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldItemName, v)
	return u
}

// UpdateItemName sets the "item_name" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateItemName() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldItemName)
	return u
}

// SetTaxRate sets the "tax_rate" field.
func (u *InvoiceRequestUpsert) SetTaxRate(v float64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldTaxRate, v)
	return u
}

// UpdateTaxRate sets the "tax_rate" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateTaxRate() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldTaxRate)
	return u
}

// AddTaxRate adds v to the "tax_rate" field.
func (u *InvoiceRequestUpsert) AddTaxRate(v float64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldTaxRate, v)
	return u
}

// SetFeeType sets the "fee_type" field.
func (u *InvoiceRequestUpsert) SetFeeType(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldFeeType, v)
	return u
}

// UpdateFeeType sets the "fee_type" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateFeeType() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldFeeType)
	return u
}

// SetFeeValue sets the "fee_value" field.
func (u *InvoiceRequestUpsert) SetFeeValue(v float64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldFeeValue, v)
	return u
}

// UpdateFeeValue sets the "fee_value" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateFeeValue() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldFeeValue)
	return u
}

// AddFeeValue adds v to the "fee_value" field.
func (u *InvoiceRequestUpsert) AddFeeValue(v float64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldFeeValue, v)
	return u
}

// SetFeeUpperAmount sets the "fee_upper_amount" field.
func (u *InvoiceRequestUpsert) SetFeeUpperAmount(v float64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldFeeUpperAmount, v)
	return u
}

// UpdateFeeUpperAmount sets the "fee_upper_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateFeeUpperAmount() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldFeeUpperAmount)
	return u
}

// AddFeeUpperAmount adds v to the "fee_upper_amount" field.
func (u *InvoiceRequestUpsert) AddFeeUpperAmount(v float64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldFeeUpperAmount, v)
	return u
}

// ClearFeeUpperAmount clears the value of the "fee_upper_amount" field.
func (u *InvoiceRequestUpsert) ClearFeeUpperAmount() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldFeeUpperAmount)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *InvoiceRequestUpsert) SetExpiresAt(v time.Time) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateExpiresAt() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldExpiresAt)
	return u
}

// SetSubmittedAt sets the "submitted_at" field.
func (u *InvoiceRequestUpsert) SetSubmittedAt(v time.Time) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldSubmittedAt, v)
	return u
}

// UpdateSubmittedAt sets the "submitted_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateSubmittedAt() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldSubmittedAt)
	return u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (u *InvoiceRequestUpsert) ClearSubmittedAt() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldSubmittedAt)
	return u
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceRequestUpsert) SetIssuedAt(v time.Time) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldIssuedAt, v)
	return u
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateIssuedAt() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldIssuedAt)
	return u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceRequestUpsert) ClearIssuedAt() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldIssuedAt)
	return u
}

// SetIssuedBy sets the "issued_by" field.
func (u *InvoiceRequestUpsert) SetIssuedBy(v int64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldIssuedBy, v)
	return u
}

// UpdateIssuedBy sets the "issued_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateIssuedBy() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldIssuedBy)
	return u
}

// AddIssuedBy adds v to the "issued_by" field.
func (u *InvoiceRequestUpsert) AddIssuedBy(v int64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldIssuedBy, v)
	return u
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (u *InvoiceRequestUpsert) ClearIssuedBy() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldIssuedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceRequestUpsertOne) UpdateNewValues() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(invoicerequest.FieldUserID)
		}
		if _, exists := u.create.mutation.OperationKey(); exists {
			s.SetIgnore(invoicerequest.FieldOperationKey)
		}
		if _, exists := u.create.mutation.Fingerprint(); exists {
			s.SetIgnore(invoicerequest.FieldFingerprint)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoicerequest.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceRequestUpsertOne) Ignore() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceRequestUpsertOne) DoNothing() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceRequestCreate.OnConflict
// documentation for more info.
func (u *InvoiceRequestUpsertOne) Update(set func(*InvoiceRequestUpsert)) *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsertOne) SetStatus(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateStatus() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetTaxID sets the "tax_id" field.
func (u *InvoiceRequestUpsertOne) SetTaxID(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTaxID(v)
	})
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateTaxID() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTaxID()
	})
}

// SetTitle sets the "title" field.
func (u *InvoiceRequestUpsertOne) SetTitle(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateTitle() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTitle()
	})
}

// SetEmail sets the "email" field.
func (u *InvoiceRequestUpsertOne) SetEmail(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateEmail() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateEmail()
	})
}

// SetRemarks sets the "remarks" field.
func (u *InvoiceRequestUpsertOne) SetRemarks(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRemarks(v)
	})
}

// UpdateRemarks sets the "remarks" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateRemarks() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRemarks()
	})
}

// SetCurrency sets the "currency" field.
func (u *InvoiceRequestUpsertOne) SetCurrency(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateCurrency() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateCurrency()
	})
}

// SetBaseAmount sets the "base_amount" field.
func (u *InvoiceRequestUpsertOne) SetBaseAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetBaseAmount(v)
	})
}

// AddBaseAmount adds v to the "base_amount" field.
func (u *InvoiceRequestUpsertOne) AddBaseAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddBaseAmount(v)
	})
}

// UpdateBaseAmount sets the "base_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateBaseAmount() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateBaseAmount()
	})
}

// SetServiceFee sets the "service_fee" field.
func (u *InvoiceRequestUpsertOne) SetServiceFee(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetServiceFee(v)
	})
}

// AddServiceFee adds v to the "service_fee" field.
func (u *InvoiceRequestUpsertOne) AddServiceFee(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddServiceFee(v)
	})
}

// UpdateServiceFee sets the "service_fee" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateServiceFee() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateServiceFee()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceRequestUpsertOne) SetTotalAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *InvoiceRequestUpsertOne) AddTotalAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateTotalAmount() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetNetAmount sets the "net_amount" field.
func (u *InvoiceRequestUpsertOne) SetNetAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetNetAmount(v)
	})
}

// AddNetAmount adds v to the "net_amount" field.
func (u *InvoiceRequestUpsertOne) AddNetAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddNetAmount(v)
	})
}

// UpdateNetAmount sets the "net_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateNetAmount() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateNetAmount()
	})
}

// SetTaxAmount sets the "tax_amount" field.
func (u *InvoiceRequestUpsertOne) SetTaxAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTaxAmount(v)
	})
}

// AddTaxAmount adds v to the "tax_amount" field.
func (u *InvoiceRequestUpsertOne) AddTaxAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddTaxAmount(v)
	})
}

// UpdateTaxAmount sets the "tax_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateTaxAmount() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTaxAmount()
	})
}

// SetItemName sets the "item_name" field.
func (u *InvoiceRequestUpsertOne) SetItemName(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetItemName(v)
	})
}

// UpdateItemName sets the "item_name" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateItemName() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateItemName()
	})
}

// SetTaxRate sets the "tax_rate" field.
func (u *InvoiceRequestUpsertOne) SetTaxRate(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTaxRate(v)
	})
}

// AddTaxRate adds v to the "tax_rate" field.
func (u *InvoiceRequestUpsertOne) AddTaxRate(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddTaxRate(v)
	})
}

// UpdateTaxRate sets the "tax_rate" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateTaxRate() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTaxRate()
	})
}

// SetFeeType sets the "fee_type" field.
func (u *InvoiceRequestUpsertOne) SetFeeType(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetFeeType(v)
	})
}

// UpdateFeeType sets the "fee_type" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateFeeType() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateFeeType()
	})
}

// SetFeeValue sets the "fee_value" field.
func (u *InvoiceRequestUpsertOne) SetFeeValue(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetFeeValue(v)
	})
}

// AddFeeValue adds v to the "fee_value" field.
func (u *InvoiceRequestUpsertOne) AddFeeValue(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddFeeValue(v)
	})
}

// UpdateFeeValue sets the "fee_value" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateFeeValue() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateFeeValue()
	})
}

// SetFeeUpperAmount sets the "fee_upper_amount" field.
func (u *InvoiceRequestUpsertOne) SetFeeUpperAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetFeeUpperAmount(v)
	})
}

// AddFeeUpperAmount adds v to the "fee_upper_amount" field.
func (u *InvoiceRequestUpsertOne) AddFeeUpperAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddFeeUpperAmount(v)
	})
}

// UpdateFeeUpperAmount sets the "fee_upper_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateFeeUpperAmount() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateFeeUpperAmount()
	})
}

// ClearFeeUpperAmount clears the value of the "fee_upper_amount" field.
func (u *InvoiceRequestUpsertOne) ClearFeeUpperAmount() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearFeeUpperAmount()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *InvoiceRequestUpsertOne) SetExpiresAt(v time.Time) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateExpiresAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetSubmittedAt sets the "submitted_at" field.
func (u *InvoiceRequestUpsertOne) SetSubmittedAt(v time.Time) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetSubmittedAt(v)
	})
}

// UpdateSubmittedAt sets the "submitted_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateSubmittedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateSubmittedAt()
	})
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (u *InvoiceRequestUpsertOne) ClearSubmittedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearSubmittedAt()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceRequestUpsertOne) SetIssuedAt(v time.Time) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateIssuedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceRequestUpsertOne) ClearIssuedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearIssuedAt()
	})
}

// SetIssuedBy sets the "issued_by" field.
func (u *InvoiceRequestUpsertOne) SetIssuedBy(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetIssuedBy(v)
	})
}

// AddIssuedBy adds v to the "issued_by" field.
func (u *InvoiceRequestUpsertOne) AddIssuedBy(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddIssuedBy(v)
	})
}

// UpdateIssuedBy sets the "issued_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateIssuedBy() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateIssuedBy()
	})
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (u *InvoiceRequestUpsertOne) ClearIssuedBy() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearIssuedBy()
	})
}

// Exec executes the query.
func (u *InvoiceRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceRequestUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceRequestUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceRequestCreateBulk is the builder for creating many InvoiceRequest entities in bulk.
type InvoiceRequestCreateBulk struct {
	config
	err      error
	builders []*InvoiceRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceRequest entities in the database.
func (_c *InvoiceRequestCreateBulk) Save(ctx context.Context) ([]*InvoiceRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceRequestCreateBulk) SaveX(ctx context.Context) []*InvoiceRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceRequestUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceRequestUpsertBulk {
	_c.conflict = opts
	return &InvoiceRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceRequestCreateBulk) OnConflictColumns(columns ...string) *InvoiceRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceRequestUpsertBulk{
		create: _c,
	}
}

// InvoiceRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceRequest nodes.
type InvoiceRequestUpsertBulk struct {
	create *InvoiceRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceRequestUpsertBulk) UpdateNewValues() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(invoicerequest.FieldUserID)
			}
			if _, exists := b.mutation.OperationKey(); exists {
				s.SetIgnore(invoicerequest.FieldOperationKey)
			}
			if _, exists := b.mutation.Fingerprint(); exists {
				s.SetIgnore(invoicerequest.FieldFingerprint)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoicerequest.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceRequestUpsertBulk) Ignore() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceRequestUpsertBulk) DoNothing() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceRequestCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceRequestUpsertBulk) Update(set func(*InvoiceRequestUpsert)) *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsertBulk) SetStatus(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateStatus() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetTaxID sets the "tax_id" field.
func (u *InvoiceRequestUpsertBulk) SetTaxID(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTaxID(v)
	})
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateTaxID() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTaxID()
	})
}

// SetTitle sets the "title" field.
func (u *InvoiceRequestUpsertBulk) SetTitle(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateTitle() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTitle()
	})
}

// SetEmail sets the "email" field.
func (u *InvoiceRequestUpsertBulk) SetEmail(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateEmail() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateEmail()
	})
}

// SetRemarks sets the "remarks" field.
func (u *InvoiceRequestUpsertBulk) SetRemarks(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRemarks(v)
	})
}

// UpdateRemarks sets the "remarks" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateRemarks() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRemarks()
	})
}

// SetCurrency sets the "currency" field.
func (u *InvoiceRequestUpsertBulk) SetCurrency(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateCurrency() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateCurrency()
	})
}

// SetBaseAmount sets the "base_amount" field.
func (u *InvoiceRequestUpsertBulk) SetBaseAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetBaseAmount(v)
	})
}

// AddBaseAmount adds v to the "base_amount" field.
func (u *InvoiceRequestUpsertBulk) AddBaseAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddBaseAmount(v)
	})
}

// UpdateBaseAmount sets the "base_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateBaseAmount() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateBaseAmount()
	})
}

// SetServiceFee sets the "service_fee" field.
func (u *InvoiceRequestUpsertBulk) SetServiceFee(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetServiceFee(v)
	})
}

// AddServiceFee adds v to the "service_fee" field.
func (u *InvoiceRequestUpsertBulk) AddServiceFee(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddServiceFee(v)
	})
}

// UpdateServiceFee sets the "service_fee" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateServiceFee() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateServiceFee()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceRequestUpsertBulk) SetTotalAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *InvoiceRequestUpsertBulk) AddTotalAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateTotalAmount() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetNetAmount sets the "net_amount" field.
func (u *InvoiceRequestUpsertBulk) SetNetAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetNetAmount(v)
	})
}

// AddNetAmount adds v to the "net_amount" field.
func (u *InvoiceRequestUpsertBulk) AddNetAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddNetAmount(v)
	})
}

// UpdateNetAmount sets the "net_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateNetAmount() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateNetAmount()
	})
}

// SetTaxAmount sets the "tax_amount" field.
func (u *InvoiceRequestUpsertBulk) SetTaxAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTaxAmount(v)
	})
}

// AddTaxAmount adds v to the "tax_amount" field.
func (u *InvoiceRequestUpsertBulk) AddTaxAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddTaxAmount(v)
	})
}

// UpdateTaxAmount sets the "tax_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateTaxAmount() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTaxAmount()
	})
}

// SetItemName sets the "item_name" field.
func (u *InvoiceRequestUpsertBulk) SetItemName(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetItemName(v)
	})
}

// UpdateItemName sets the "item_name" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateItemName() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateItemName()
	})
}

// SetTaxRate sets the "tax_rate" field.
func (u *InvoiceRequestUpsertBulk) SetTaxRate(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTaxRate(v)
	})
}

// AddTaxRate adds v to the "tax_rate" field.
func (u *InvoiceRequestUpsertBulk) AddTaxRate(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddTaxRate(v)
	})
}

// UpdateTaxRate sets the "tax_rate" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateTaxRate() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTaxRate()
	})
}

// SetFeeType sets the "fee_type" field.
func (u *InvoiceRequestUpsertBulk) SetFeeType(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetFeeType(v)
	})
}

// UpdateFeeType sets the "fee_type" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateFeeType() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateFeeType()
	})
}

// SetFeeValue sets the "fee_value" field.
func (u *InvoiceRequestUpsertBulk) SetFeeValue(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetFeeValue(v)
	})
}

// AddFeeValue adds v to the "fee_value" field.
func (u *InvoiceRequestUpsertBulk) AddFeeValue(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddFeeValue(v)
	})
}

// UpdateFeeValue sets the "fee_value" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateFeeValue() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateFeeValue()
	})
}

// SetFeeUpperAmount sets the "fee_upper_amount" field.
func (u *InvoiceRequestUpsertBulk) SetFeeUpperAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetFeeUpperAmount(v)
	})
}

// AddFeeUpperAmount adds v to the "fee_upper_amount" field.
func (u *InvoiceRequestUpsertBulk) AddFeeUpperAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddFeeUpperAmount(v)
	})
}

// UpdateFeeUpperAmount sets the "fee_upper_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateFeeUpperAmount() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateFeeUpperAmount()
	})
}

// ClearFeeUpperAmount clears the value of the "fee_upper_amount" field.
func (u *InvoiceRequestUpsertBulk) ClearFeeUpperAmount() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearFeeUpperAmount()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *InvoiceRequestUpsertBulk) SetExpiresAt(v time.Time) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateExpiresAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetSubmittedAt sets the "submitted_at" field.
func (u *InvoiceRequestUpsertBulk) SetSubmittedAt(v time.Time) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetSubmittedAt(v)
	})
}

// UpdateSubmittedAt sets the "submitted_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateSubmittedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateSubmittedAt()
	})
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (u *InvoiceRequestUpsertBulk) ClearSubmittedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearSubmittedAt()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceRequestUpsertBulk) SetIssuedAt(v time.Time) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateIssuedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceRequestUpsertBulk) ClearIssuedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearIssuedAt()
	})
}

// SetIssuedBy sets the "issued_by" field.
func (u *InvoiceRequestUpsertBulk) SetIssuedBy(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetIssuedBy(v)
	})
}

// AddIssuedBy adds v to the "issued_by" field.
func (u *InvoiceRequestUpsertBulk) AddIssuedBy(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddIssuedBy(v)
	})
}

// UpdateIssuedBy sets the "issued_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateIssuedBy() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateIssuedBy()
	})
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (u *InvoiceRequestUpsertBulk) ClearIssuedBy() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearIssuedBy()
	})
}

// Exec executes the query.
func (u *InvoiceRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
