// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoicerequestorder"
)

// InvoiceRequestOrderCreate is the builder for creating a InvoiceRequestOrder entity.
type InvoiceRequestOrderCreate struct {
	config
	mutation *InvoiceRequestOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInvoiceRequestID sets the "invoice_request_id" field.
func (_c *InvoiceRequestOrderCreate) SetInvoiceRequestID(v int64) *InvoiceRequestOrderCreate {
	_c.mutation.SetInvoiceRequestID(v)
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *InvoiceRequestOrderCreate) SetOrderID(v int64) *InvoiceRequestOrderCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetOrderNo sets the "order_no" field.
func (_c *InvoiceRequestOrderCreate) SetOrderNo(v string) *InvoiceRequestOrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetOrderType sets the "order_type" field.
func (_c *InvoiceRequestOrderCreate) SetOrderType(v string) *InvoiceRequestOrderCreate {
	_c.mutation.SetOrderType(v)
	return _c
}

// SetName sets the "name" field.
func (_c *InvoiceRequestOrderCreate) SetName(v string) *InvoiceRequestOrderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *InvoiceRequestOrderCreate) SetAmount(v float64) *InvoiceRequestOrderCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetReleasedAt sets the "released_at" field.
func (_c *InvoiceRequestOrderCreate) SetReleasedAt(v time.Time) *InvoiceRequestOrderCreate {
	_c.mutation.SetReleasedAt(v)
	return _c
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_c *InvoiceRequestOrderCreate) SetNillableReleasedAt(v *time.Time) *InvoiceRequestOrderCreate {
	if v != nil {
		_c.SetReleasedAt(*v)
	}
	return _c
}

// Mutation returns the InvoiceRequestOrderMutation object of the builder.
func (_c *InvoiceRequestOrderCreate) Mutation() *InvoiceRequestOrderMutation {
	return _c.mutation
}

// Save creates the InvoiceRequestOrder in the database.
func (_c *InvoiceRequestOrderCreate) Save(ctx context.Context) (*InvoiceRequestOrder, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceRequestOrderCreate) SaveX(ctx context.Context) *InvoiceRequestOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceRequestOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceRequestOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceRequestOrderCreate) check() error {
	if _, ok := _c.mutation.InvoiceRequestID(); !ok {
		return &ValidationError{Name: "invoice_request_id", err: errors.New(`ent: missing required field "InvoiceRequestOrder.invoice_request_id"`)}
	}
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "InvoiceRequestOrder.order_id"`)}
	}
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "InvoiceRequestOrder.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := invoicerequestorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequestOrder.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrderType(); !ok {
		return &ValidationError{Name: "order_type", err: errors.New(`ent: missing required field "InvoiceRequestOrder.order_type"`)}
	}
	if v, ok := _c.mutation.OrderType(); ok {
		if err := invoicerequestorder.OrderTypeValidator(v); err != nil {
			return &ValidationError{Name: "order_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequestOrder.order_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "InvoiceRequestOrder.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := invoicerequestorder.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequestOrder.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "InvoiceRequestOrder.amount"`)}
	}
	return nil
}

func (_c *InvoiceRequestOrderCreate) sqlSave(ctx context.Context) (*InvoiceRequestOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceRequestOrderCreate) createSpec() (*InvoiceRequestOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceRequestOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoicerequestorder.Table, sqlgraph.NewFieldSpec(invoicerequestorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.InvoiceRequestID(); ok {
		_spec.SetField(invoicerequestorder.FieldInvoiceRequestID, field.TypeInt64, value)
		_node.InvoiceRequestID = value
	}
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(invoicerequestorder.FieldOrderID, field.TypeInt64, value)
		_node.OrderID = value
	}
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(invoicerequestorder.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.OrderType(); ok {
		_spec.SetField(invoicerequestorder.FieldOrderType, field.TypeString, value)
		_node.OrderType = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(invoicerequestorder.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(invoicerequestorder.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.ReleasedAt(); ok {
		_spec.SetField(invoicerequestorder.FieldReleasedAt, field.TypeTime, value)
		_node.ReleasedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceRequestOrder.Create().
//		SetInvoiceRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceRequestOrderUpsert) {
//			SetInvoiceRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceRequestOrderCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceRequestOrderUpsertOne {
	_c.conflict = opts
	return &InvoiceRequestOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceRequestOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceRequestOrderCreate) OnConflictColumns(columns ...string) *InvoiceRequestOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceRequestOrderUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceRequestOrderUpsertOne is the builder for "upsert"-ing
	//  one InvoiceRequestOrder node.
	InvoiceRequestOrderUpsertOne struct {
		create *InvoiceRequestOrderCreate
	}

	// InvoiceRequestOrderUpsert is the "OnConflict" setter.
	InvoiceRequestOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetReleasedAt sets the "released_at" field.
func (u *InvoiceRequestOrderUpsert) SetReleasedAt(v time.Time) *InvoiceRequestOrderUpsert {
	u.Set(invoicerequestorder.FieldReleasedAt, v)
	return u
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *InvoiceRequestOrderUpsert) UpdateReleasedAt() *InvoiceRequestOrderUpsert {
	u.SetExcluded(invoicerequestorder.FieldReleasedAt)
	return u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *InvoiceRequestOrderUpsert) ClearReleasedAt() *InvoiceRequestOrderUpsert {
	u.SetNull(invoicerequestorder.FieldReleasedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceRequestOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceRequestOrderUpsertOne) UpdateNewValues() *InvoiceRequestOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.InvoiceRequestID(); exists {
			s.SetIgnore(invoicerequestorder.FieldInvoiceRequestID)
		}
		if _, exists := u.create.mutation.OrderID(); exists {
			s.SetIgnore(invoicerequestorder.FieldOrderID)
		}
		if _, exists := u.create.mutation.OrderNo(); exists {
			s.SetIgnore(invoicerequestorder.FieldOrderNo)
		}
		if _, exists := u.create.mutation.OrderType(); exists {
			s.SetIgnore(invoicerequestorder.FieldOrderType)
		}
		if _, exists := u.create.mutation.Name(); exists {
			s.SetIgnore(invoicerequestorder.FieldName)
		}
		if _, exists := u.create.mutation.Amount(); exists {
			s.SetIgnore(invoicerequestorder.FieldAmount)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceRequestOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceRequestOrderUpsertOne) Ignore() *InvoiceRequestOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceRequestOrderUpsertOne) DoNothing() *InvoiceRequestOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceRequestOrderCreate.OnConflict
// documentation for more info.
func (u *InvoiceRequestOrderUpsertOne) Update(set func(*InvoiceRequestOrderUpsert)) *InvoiceRequestOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceRequestOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetReleasedAt sets the "released_at" field.
func (u *InvoiceRequestOrderUpsertOne) SetReleasedAt(v time.Time) *InvoiceRequestOrderUpsertOne {
	return u.Update(func(s *InvoiceRequestOrderUpsert) {
		s.SetReleasedAt(v)
	})
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *InvoiceRequestOrderUpsertOne) UpdateReleasedAt() *InvoiceRequestOrderUpsertOne {
	return u.Update(func(s *InvoiceRequestOrderUpsert) {
		s.UpdateReleasedAt()
	})
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *InvoiceRequestOrderUpsertOne) ClearReleasedAt() *InvoiceRequestOrderUpsertOne {
	return u.Update(func(s *InvoiceRequestOrderUpsert) {
		s.ClearReleasedAt()
	})
}

// Exec executes the query.
func (u *InvoiceRequestOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceRequestOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceRequestOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceRequestOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceRequestOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceRequestOrderCreateBulk is the builder for creating many InvoiceRequestOrder entities in bulk.
type InvoiceRequestOrderCreateBulk struct {
	config
	err      error
	builders []*InvoiceRequestOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceRequestOrder entities in the database.
func (_c *InvoiceRequestOrderCreateBulk) Save(ctx context.Context) ([]*InvoiceRequestOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceRequestOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceRequestOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceRequestOrderCreateBulk) SaveX(ctx context.Context) []*InvoiceRequestOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceRequestOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceRequestOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceRequestOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceRequestOrderUpsert) {
//			SetInvoiceRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceRequestOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceRequestOrderUpsertBulk {
	_c.conflict = opts
	return &InvoiceRequestOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceRequestOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceRequestOrderCreateBulk) OnConflictColumns(columns ...string) *InvoiceRequestOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceRequestOrderUpsertBulk{
		create: _c,
	}
}

// InvoiceRequestOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceRequestOrder nodes.
type InvoiceRequestOrderUpsertBulk struct {
	create *InvoiceRequestOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceRequestOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceRequestOrderUpsertBulk) UpdateNewValues() *InvoiceRequestOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.InvoiceRequestID(); exists {
				s.SetIgnore(invoicerequestorder.FieldInvoiceRequestID)
			}
			if _, exists := b.mutation.OrderID(); exists {
				s.SetIgnore(invoicerequestorder.FieldOrderID)
			}
			if _, exists := b.mutation.OrderNo(); exists {
				s.SetIgnore(invoicerequestorder.FieldOrderNo)
			}
			if _, exists := b.mutation.OrderType(); exists {
				s.SetIgnore(invoicerequestorder.FieldOrderType)
			}
			if _, exists := b.mutation.Name(); exists {
				s.SetIgnore(invoicerequestorder.FieldName)
			}
			if _, exists := b.mutation.Amount(); exists {
				s.SetIgnore(invoicerequestorder.FieldAmount)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceRequestOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceRequestOrderUpsertBulk) Ignore() *InvoiceRequestOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceRequestOrderUpsertBulk) DoNothing() *InvoiceRequestOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceRequestOrderCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceRequestOrderUpsertBulk) Update(set func(*InvoiceRequestOrderUpsert)) *InvoiceRequestOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceRequestOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetReleasedAt sets the "released_at" field.
func (u *InvoiceRequestOrderUpsertBulk) SetReleasedAt(v time.Time) *InvoiceRequestOrderUpsertBulk {
	return u.Update(func(s *InvoiceRequestOrderUpsert) {
		s.SetReleasedAt(v)
	})
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *InvoiceRequestOrderUpsertBulk) UpdateReleasedAt() *InvoiceRequestOrderUpsertBulk {
	return u.Update(func(s *InvoiceRequestOrderUpsert) {
		s.UpdateReleasedAt()
	})
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *InvoiceRequestOrderUpsertBulk) ClearReleasedAt() *InvoiceRequestOrderUpsertBulk {
	return u.Update(func(s *InvoiceRequestOrderUpsert) {
		s.ClearReleasedAt()
	})
}

// Exec executes the query.
func (u *InvoiceRequestOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceRequestOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceRequestOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceRequestOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
