// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoicerequestorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// InvoiceRequestOrderUpdate is the builder for updating InvoiceRequestOrder entities.
type InvoiceRequestOrderUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceRequestOrderMutation
}

// Where appends a list predicates to the InvoiceRequestOrderUpdate builder.
func (_u *InvoiceRequestOrderUpdate) Where(ps ...predicate.InvoiceRequestOrder) *InvoiceRequestOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetReleasedAt sets the "released_at" field.
func (_u *InvoiceRequestOrderUpdate) SetReleasedAt(v time.Time) *InvoiceRequestOrderUpdate {
	_u.mutation.SetReleasedAt(v)
	return _u
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_u *InvoiceRequestOrderUpdate) SetNillableReleasedAt(v *time.Time) *InvoiceRequestOrderUpdate {
	if v != nil {
		_u.SetReleasedAt(*v)
	}
	return _u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (_u *InvoiceRequestOrderUpdate) ClearReleasedAt() *InvoiceRequestOrderUpdate {
	_u.mutation.ClearReleasedAt()
	return _u
}

// Mutation returns the InvoiceRequestOrderMutation object of the builder.
func (_u *InvoiceRequestOrderUpdate) Mutation() *InvoiceRequestOrderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceRequestOrderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceRequestOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceRequestOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceRequestOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *InvoiceRequestOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(invoicerequestorder.Table, invoicerequestorder.Columns, sqlgraph.NewFieldSpec(invoicerequestorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReleasedAt(); ok {
		_spec.SetField(invoicerequestorder.FieldReleasedAt, field.TypeTime, value)
	}
	if _u.mutation.ReleasedAtCleared() {
		_spec.ClearField(invoicerequestorder.FieldReleasedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoicerequestorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceRequestOrderUpdateOne is the builder for updating a single InvoiceRequestOrder entity.
type InvoiceRequestOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceRequestOrderMutation
}

// SetReleasedAt sets the "released_at" field.
func (_u *InvoiceRequestOrderUpdateOne) SetReleasedAt(v time.Time) *InvoiceRequestOrderUpdateOne {
	_u.mutation.SetReleasedAt(v)
	return _u
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_u *InvoiceRequestOrderUpdateOne) SetNillableReleasedAt(v *time.Time) *InvoiceRequestOrderUpdateOne {
	if v != nil {
		_u.SetReleasedAt(*v)
	}
	return _u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (_u *InvoiceRequestOrderUpdateOne) ClearReleasedAt() *InvoiceRequestOrderUpdateOne {
	_u.mutation.ClearReleasedAt()
	return _u
}

// Mutation returns the InvoiceRequestOrderMutation object of the builder.
func (_u *InvoiceRequestOrderUpdateOne) Mutation() *InvoiceRequestOrderMutation {
	return _u.mutation
}

// Where appends a list predicates to the InvoiceRequestOrderUpdate builder.
func (_u *InvoiceRequestOrderUpdateOne) Where(ps ...predicate.InvoiceRequestOrder) *InvoiceRequestOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceRequestOrderUpdateOne) Select(field string, fields ...string) *InvoiceRequestOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvoiceRequestOrder entity.
func (_u *InvoiceRequestOrderUpdateOne) Save(ctx context.Context) (*InvoiceRequestOrder, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceRequestOrderUpdateOne) SaveX(ctx context.Context) *InvoiceRequestOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceRequestOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceRequestOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *InvoiceRequestOrderUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceRequestOrder, err error) {
	_spec := sqlgraph.NewUpdateSpec(invoicerequestorder.Table, invoicerequestorder.Columns, sqlgraph.NewFieldSpec(invoicerequestorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceRequestOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoicerequestorder.FieldID)
		for _, f := range fields {
			if !invoicerequestorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoicerequestorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReleasedAt(); ok {
		_spec.SetField(invoicerequestorder.FieldReleasedAt, field.TypeTime, value)
	}
	if _u.mutation.ReleasedAtCleared() {
		_spec.ClearField(invoicerequestorder.FieldReleasedAt, field.TypeTime)
	}
	_node = &InvoiceRequestOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoicerequestorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
