// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/subscriptiondiscountcode"
)

// SubscriptionDiscountCode is the model entity for the SubscriptionDiscountCode schema.
type SubscriptionDiscountCode struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// DiscountType holds the value of the "discount_type" field.
	DiscountType string `json:"discount_type,omitempty"`
	// DiscountValue holds the value of the "discount_value" field.
	DiscountValue float64 `json:"discount_value,omitempty"`
	// PlanIds holds the value of the "plan_ids" field.
	PlanIds []int64 `json:"plan_ids,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// MaxUses holds the value of the "max_uses" field.
	MaxUses int `json:"max_uses,omitempty"`
	// PerUserLimit holds the value of the "per_user_limit" field.
	PerUserLimit int `json:"per_user_limit,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionDiscountCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptiondiscountcode.FieldPlanIds:
			values[i] = new([]byte)
		case subscriptiondiscountcode.FieldEnabled:
			values[i] = new(sql.NullBool)
		case subscriptiondiscountcode.FieldDiscountValue:
			values[i] = new(sql.NullFloat64)
		case subscriptiondiscountcode.FieldID, subscriptiondiscountcode.FieldMaxUses, subscriptiondiscountcode.FieldPerUserLimit:
			values[i] = new(sql.NullInt64)
		case subscriptiondiscountcode.FieldCode, subscriptiondiscountcode.FieldDiscountType:
			values[i] = new(sql.NullString)
		case subscriptiondiscountcode.FieldExpiresAt, subscriptiondiscountcode.FieldCreatedAt, subscriptiondiscountcode.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionDiscountCode fields.
func (_m *SubscriptionDiscountCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptiondiscountcode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptiondiscountcode.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case subscriptiondiscountcode.FieldDiscountType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field discount_type", values[i])
			} else if value.Valid {
				_m.DiscountType = value.String
			}
		case subscriptiondiscountcode.FieldDiscountValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field discount_value", values[i])
			} else if value.Valid {
				_m.DiscountValue = value.Float64
			}
		case subscriptiondiscountcode.FieldPlanIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field plan_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PlanIds); err != nil {
					return fmt.Errorf("unmarshal field plan_ids: %w", err)
				}
			}
		case subscriptiondiscountcode.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case subscriptiondiscountcode.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case subscriptiondiscountcode.FieldMaxUses:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_uses", values[i])
			} else if value.Valid {
				_m.MaxUses = int(value.Int64)
			}
		case subscriptiondiscountcode.FieldPerUserLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field per_user_limit", values[i])
			} else if value.Valid {
				_m.PerUserLimit = int(value.Int64)
			}
		case subscriptiondiscountcode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptiondiscountcode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionDiscountCode.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionDiscountCode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SubscriptionDiscountCode.
// Note that you need to call SubscriptionDiscountCode.Unwrap() before calling this method if this SubscriptionDiscountCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionDiscountCode) Update() *SubscriptionDiscountCodeUpdateOne {
	return NewSubscriptionDiscountCodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionDiscountCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionDiscountCode) Unwrap() *SubscriptionDiscountCode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionDiscountCode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionDiscountCode) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionDiscountCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("discount_type=")
	builder.WriteString(_m.DiscountType)
	builder.WriteString(", ")
	builder.WriteString("discount_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiscountValue))
	builder.WriteString(", ")
	builder.WriteString("plan_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlanIds))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("max_uses=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxUses))
	builder.WriteString(", ")
	builder.WriteString("per_user_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.PerUserLimit))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionDiscountCodes is a parsable slice of SubscriptionDiscountCode.
type SubscriptionDiscountCodes []*SubscriptionDiscountCode
