// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptiondiscountcode"
)

// SubscriptionDiscountCodeUpdate is the builder for updating SubscriptionDiscountCode entities.
type SubscriptionDiscountCodeUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionDiscountCodeMutation
}

// Where appends a list predicates to the SubscriptionDiscountCodeUpdate builder.
func (_u *SubscriptionDiscountCodeUpdate) Where(ps ...predicate.SubscriptionDiscountCode) *SubscriptionDiscountCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDiscountType sets the "discount_type" field.
func (_u *SubscriptionDiscountCodeUpdate) SetDiscountType(v string) *SubscriptionDiscountCodeUpdate {
	_u.mutation.SetDiscountType(v)
	return _u
}

// SetNillableDiscountType sets the "discount_type" field if the given value is not nil.
func (_u *SubscriptionDiscountCodeUpdate) SetNillableDiscountType(v *string) *SubscriptionDiscountCodeUpdate {
	if v != nil {
		_u.SetDiscountType(*v)
	}
	return _u
}

// SetDiscountValue sets the "discount_value" field.
func (_u *SubscriptionDiscountCodeUpdate) SetDiscountValue(v float64) *SubscriptionDiscountCodeUpdate {
	_u.mutation.ResetDiscountValue()
	_u.mutation.SetDiscountValue(v)
	return _u
}

// SetNillableDiscountValue sets the "discount_value" field if the given value is not nil.
func (_u *SubscriptionDiscountCodeUpdate) SetNillableDiscountValue(v *float64) *SubscriptionDiscountCodeUpdate {
	if v != nil {
		_u.SetDiscountValue(*v)
	}
	return _u
}

// AddDiscountValue adds value to the "discount_value" field.
func (_u *SubscriptionDiscountCodeUpdate) AddDiscountValue(v float64) *SubscriptionDiscountCodeUpdate {
	_u.mutation.AddDiscountValue(v)
	return _u
}

// SetPlanIds sets the "plan_ids" field.
func (_u *SubscriptionDiscountCodeUpdate) SetPlanIds(v []int64) *SubscriptionDiscountCodeUpdate {
	_u.mutation.SetPlanIds(v)
	return _u
}

// AppendPlanIds appends value to the "plan_ids" field.
func (_u *SubscriptionDiscountCodeUpdate) AppendPlanIds(v []int64) *SubscriptionDiscountCodeUpdate {
	_u.mutation.AppendPlanIds(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SubscriptionDiscountCodeUpdate) SetEnabled(v bool) *SubscriptionDiscountCodeUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SubscriptionDiscountCodeUpdate) SetNillableEnabled(v *bool) *SubscriptionDiscountCodeUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionDiscountCodeUpdate) SetExpiresAt(v time.Time) *SubscriptionDiscountCodeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionDiscountCodeUpdate) SetNillableExpiresAt(v *time.Time) *SubscriptionDiscountCodeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *SubscriptionDiscountCodeUpdate) ClearExpiresAt() *SubscriptionDiscountCodeUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetMaxUses sets the "max_uses" field.
func (_u *SubscriptionDiscountCodeUpdate) SetMaxUses(v int) *SubscriptionDiscountCodeUpdate {
	_u.mutation.ResetMaxUses()
	_u.mutation.SetMaxUses(v)
	return _u
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_u *SubscriptionDiscountCodeUpdate) SetNillableMaxUses(v *int) *SubscriptionDiscountCodeUpdate {
	if v != nil {
		_u.SetMaxUses(*v)
	}
	return _u
}

// AddMaxUses adds value to the "max_uses" field.
func (_u *SubscriptionDiscountCodeUpdate) AddMaxUses(v int) *SubscriptionDiscountCodeUpdate {
	_u.mutation.AddMaxUses(v)
	return _u
}

// SetPerUserLimit sets the "per_user_limit" field.
func (_u *SubscriptionDiscountCodeUpdate) SetPerUserLimit(v int) *SubscriptionDiscountCodeUpdate {
	_u.mutation.ResetPerUserLimit()
	_u.mutation.SetPerUserLimit(v)
	return _u
}

// SetNillablePerUserLimit sets the "per_user_limit" field if the given value is not nil.
func (_u *SubscriptionDiscountCodeUpdate) SetNillablePerUserLimit(v *int) *SubscriptionDiscountCodeUpdate {
	if v != nil {
		_u.SetPerUserLimit(*v)
	}
	return _u
}

// AddPerUserLimit adds value to the "per_user_limit" field.
func (_u *SubscriptionDiscountCodeUpdate) AddPerUserLimit(v int) *SubscriptionDiscountCodeUpdate {
	_u.mutation.AddPerUserLimit(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionDiscountCodeUpdate) SetUpdatedAt(v time.Time) *SubscriptionDiscountCodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SubscriptionDiscountCodeMutation object of the builder.
func (_u *SubscriptionDiscountCodeUpdate) Mutation() *SubscriptionDiscountCodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionDiscountCodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionDiscountCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionDiscountCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionDiscountCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionDiscountCodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptiondiscountcode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionDiscountCodeUpdate) check() error {
	if v, ok := _u.mutation.DiscountType(); ok {
		if err := subscriptiondiscountcode.DiscountTypeValidator(v); err != nil {
			return &ValidationError{Name: "discount_type", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDiscountCode.discount_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxUses(); ok {
		if err := subscriptiondiscountcode.MaxUsesValidator(v); err != nil {
			return &ValidationError{Name: "max_uses", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDiscountCode.max_uses": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PerUserLimit(); ok {
		if err := subscriptiondiscountcode.PerUserLimitValidator(v); err != nil {
			return &ValidationError{Name: "per_user_limit", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDiscountCode.per_user_limit": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionDiscountCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptiondiscountcode.Table, subscriptiondiscountcode.Columns, sqlgraph.NewFieldSpec(subscriptiondiscountcode.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DiscountType(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldDiscountType, field.TypeString, value)
	}
	if value, ok := _u.mutation.DiscountValue(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldDiscountValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountValue(); ok {
		_spec.AddField(subscriptiondiscountcode.FieldDiscountValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PlanIds(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldPlanIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPlanIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, subscriptiondiscountcode.FieldPlanIds, value)
		})
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(subscriptiondiscountcode.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MaxUses(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUses(); ok {
		_spec.AddField(subscriptiondiscountcode.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PerUserLimit(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldPerUserLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPerUserLimit(); ok {
		_spec.AddField(subscriptiondiscountcode.FieldPerUserLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptiondiscountcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionDiscountCodeUpdateOne is the builder for updating a single SubscriptionDiscountCode entity.
type SubscriptionDiscountCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionDiscountCodeMutation
}

// SetDiscountType sets the "discount_type" field.
func (_u *SubscriptionDiscountCodeUpdateOne) SetDiscountType(v string) *SubscriptionDiscountCodeUpdateOne {
	_u.mutation.SetDiscountType(v)
	return _u
}

// SetNillableDiscountType sets the "discount_type" field if the given value is not nil.
func (_u *SubscriptionDiscountCodeUpdateOne) SetNillableDiscountType(v *string) *SubscriptionDiscountCodeUpdateOne {
	if v != nil {
		_u.SetDiscountType(*v)
	}
	return _u
}

// SetDiscountValue sets the "discount_value" field.
func (_u *SubscriptionDiscountCodeUpdateOne) SetDiscountValue(v float64) *SubscriptionDiscountCodeUpdateOne {
	_u.mutation.ResetDiscountValue()
	_u.mutation.SetDiscountValue(v)
	return _u
}

// SetNillableDiscountValue sets the "discount_value" field if the given value is not nil.
func (_u *SubscriptionDiscountCodeUpdateOne) SetNillableDiscountValue(v *float64) *SubscriptionDiscountCodeUpdateOne {
	if v != nil {
		_u.SetDiscountValue(*v)
	}
	return _u
}

// AddDiscountValue adds value to the "discount_value" field.
func (_u *SubscriptionDiscountCodeUpdateOne) AddDiscountValue(v float64) *SubscriptionDiscountCodeUpdateOne {
	_u.mutation.AddDiscountValue(v)
	return _u
}

// SetPlanIds sets the "plan_ids" field.
func (_u *SubscriptionDiscountCodeUpdateOne) SetPlanIds(v []int64) *SubscriptionDiscountCodeUpdateOne {
	_u.mutation.SetPlanIds(v)
	return _u
}

// AppendPlanIds appends value to the "plan_ids" field.
func (_u *SubscriptionDiscountCodeUpdateOne) AppendPlanIds(v []int64) *SubscriptionDiscountCodeUpdateOne {
	_u.mutation.AppendPlanIds(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SubscriptionDiscountCodeUpdateOne) SetEnabled(v bool) *SubscriptionDiscountCodeUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SubscriptionDiscountCodeUpdateOne) SetNillableEnabled(v *bool) *SubscriptionDiscountCodeUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionDiscountCodeUpdateOne) SetExpiresAt(v time.Time) *SubscriptionDiscountCodeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionDiscountCodeUpdateOne) SetNillableExpiresAt(v *time.Time) *SubscriptionDiscountCodeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *SubscriptionDiscountCodeUpdateOne) ClearExpiresAt() *SubscriptionDiscountCodeUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetMaxUses sets the "max_uses" field.
func (_u *SubscriptionDiscountCodeUpdateOne) SetMaxUses(v int) *SubscriptionDiscountCodeUpdateOne {
	_u.mutation.ResetMaxUses()
	_u.mutation.SetMaxUses(v)
	return _u
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_u *SubscriptionDiscountCodeUpdateOne) SetNillableMaxUses(v *int) *SubscriptionDiscountCodeUpdateOne {
	if v != nil {
		_u.SetMaxUses(*v)
	}
	return _u
}

// AddMaxUses adds value to the "max_uses" field.
func (_u *SubscriptionDiscountCodeUpdateOne) AddMaxUses(v int) *SubscriptionDiscountCodeUpdateOne {
	_u.mutation.AddMaxUses(v)
	return _u
}

// SetPerUserLimit sets the "per_user_limit" field.
func (_u *SubscriptionDiscountCodeUpdateOne) SetPerUserLimit(v int) *SubscriptionDiscountCodeUpdateOne {
	_u.mutation.ResetPerUserLimit()
	_u.mutation.SetPerUserLimit(v)
	return _u
}

// SetNillablePerUserLimit sets the "per_user_limit" field if the given value is not nil.
func (_u *SubscriptionDiscountCodeUpdateOne) SetNillablePerUserLimit(v *int) *SubscriptionDiscountCodeUpdateOne {
	if v != nil {
		_u.SetPerUserLimit(*v)
	}
	return _u
}

// AddPerUserLimit adds value to the "per_user_limit" field.
func (_u *SubscriptionDiscountCodeUpdateOne) AddPerUserLimit(v int) *SubscriptionDiscountCodeUpdateOne {
	_u.mutation.AddPerUserLimit(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionDiscountCodeUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionDiscountCodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SubscriptionDiscountCodeMutation object of the builder.
func (_u *SubscriptionDiscountCodeUpdateOne) Mutation() *SubscriptionDiscountCodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the SubscriptionDiscountCodeUpdate builder.
func (_u *SubscriptionDiscountCodeUpdateOne) Where(ps ...predicate.SubscriptionDiscountCode) *SubscriptionDiscountCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionDiscountCodeUpdateOne) Select(field string, fields ...string) *SubscriptionDiscountCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionDiscountCode entity.
func (_u *SubscriptionDiscountCodeUpdateOne) Save(ctx context.Context) (*SubscriptionDiscountCode, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionDiscountCodeUpdateOne) SaveX(ctx context.Context) *SubscriptionDiscountCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionDiscountCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionDiscountCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionDiscountCodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptiondiscountcode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionDiscountCodeUpdateOne) check() error {
	if v, ok := _u.mutation.DiscountType(); ok {
		if err := subscriptiondiscountcode.DiscountTypeValidator(v); err != nil {
			return &ValidationError{Name: "discount_type", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDiscountCode.discount_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxUses(); ok {
		if err := subscriptiondiscountcode.MaxUsesValidator(v); err != nil {
			return &ValidationError{Name: "max_uses", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDiscountCode.max_uses": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PerUserLimit(); ok {
		if err := subscriptiondiscountcode.PerUserLimitValidator(v); err != nil {
			return &ValidationError{Name: "per_user_limit", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDiscountCode.per_user_limit": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionDiscountCodeUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionDiscountCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptiondiscountcode.Table, subscriptiondiscountcode.Columns, sqlgraph.NewFieldSpec(subscriptiondiscountcode.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionDiscountCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptiondiscountcode.FieldID)
		for _, f := range fields {
			if !subscriptiondiscountcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptiondiscountcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DiscountType(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldDiscountType, field.TypeString, value)
	}
	if value, ok := _u.mutation.DiscountValue(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldDiscountValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountValue(); ok {
		_spec.AddField(subscriptiondiscountcode.FieldDiscountValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PlanIds(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldPlanIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPlanIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, subscriptiondiscountcode.FieldPlanIds, value)
		})
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(subscriptiondiscountcode.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MaxUses(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUses(); ok {
		_spec.AddField(subscriptiondiscountcode.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PerUserLimit(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldPerUserLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPerUserLimit(); ok {
		_spec.AddField(subscriptiondiscountcode.FieldPerUserLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SubscriptionDiscountCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptiondiscountcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
