// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/subscriptiondiscountcode"
)

// SubscriptionDiscountCodeCreate is the builder for creating a SubscriptionDiscountCode entity.
type SubscriptionDiscountCodeCreate struct {
	config
	mutation *SubscriptionDiscountCodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCode sets the "code" field.
func (_c *SubscriptionDiscountCodeCreate) SetCode(v string) *SubscriptionDiscountCodeCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetDiscountType sets the "discount_type" field.
func (_c *SubscriptionDiscountCodeCreate) SetDiscountType(v string) *SubscriptionDiscountCodeCreate {
	_c.mutation.SetDiscountType(v)
	return _c
}

// SetDiscountValue sets the "discount_value" field.
func (_c *SubscriptionDiscountCodeCreate) SetDiscountValue(v float64) *SubscriptionDiscountCodeCreate {
	_c.mutation.SetDiscountValue(v)
	return _c
}

// SetPlanIds sets the "plan_ids" field.
func (_c *SubscriptionDiscountCodeCreate) SetPlanIds(v []int64) *SubscriptionDiscountCodeCreate {
	_c.mutation.SetPlanIds(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *SubscriptionDiscountCodeCreate) SetEnabled(v bool) *SubscriptionDiscountCodeCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *SubscriptionDiscountCodeCreate) SetNillableEnabled(v *bool) *SubscriptionDiscountCodeCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *SubscriptionDiscountCodeCreate) SetExpiresAt(v time.Time) *SubscriptionDiscountCodeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *SubscriptionDiscountCodeCreate) SetNillableExpiresAt(v *time.Time) *SubscriptionDiscountCodeCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetMaxUses sets the "max_uses" field.
func (_c *SubscriptionDiscountCodeCreate) SetMaxUses(v int) *SubscriptionDiscountCodeCreate {
	_c.mutation.SetMaxUses(v)
	return _c
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_c *SubscriptionDiscountCodeCreate) SetNillableMaxUses(v *int) *SubscriptionDiscountCodeCreate {
	if v != nil {
		_c.SetMaxUses(*v)
	}
	return _c
}

// SetPerUserLimit sets the "per_user_limit" field.
func (_c *SubscriptionDiscountCodeCreate) SetPerUserLimit(v int) *SubscriptionDiscountCodeCreate {
	_c.mutation.SetPerUserLimit(v)
	return _c
}

// SetNillablePerUserLimit sets the "per_user_limit" field if the given value is not nil.
func (_c *SubscriptionDiscountCodeCreate) SetNillablePerUserLimit(v *int) *SubscriptionDiscountCodeCreate {
	if v != nil {
		_c.SetPerUserLimit(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionDiscountCodeCreate) SetCreatedAt(v time.Time) *SubscriptionDiscountCodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionDiscountCodeCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionDiscountCodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionDiscountCodeCreate) SetUpdatedAt(v time.Time) *SubscriptionDiscountCodeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionDiscountCodeCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionDiscountCodeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the SubscriptionDiscountCodeMutation object of the builder.
func (_c *SubscriptionDiscountCodeCreate) Mutation() *SubscriptionDiscountCodeMutation {
	return _c.mutation
}

// Save creates the SubscriptionDiscountCode in the database.
func (_c *SubscriptionDiscountCodeCreate) Save(ctx context.Context) (*SubscriptionDiscountCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionDiscountCodeCreate) SaveX(ctx context.Context) *SubscriptionDiscountCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionDiscountCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionDiscountCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionDiscountCodeCreate) defaults() {
	if _, ok := _c.mutation.PlanIds(); !ok {
		v := subscriptiondiscountcode.DefaultPlanIds
		_c.mutation.SetPlanIds(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := subscriptiondiscountcode.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.MaxUses(); !ok {
		v := subscriptiondiscountcode.DefaultMaxUses
		_c.mutation.SetMaxUses(v)
	}
	if _, ok := _c.mutation.PerUserLimit(); !ok {
		v := subscriptiondiscountcode.DefaultPerUserLimit
		_c.mutation.SetPerUserLimit(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptiondiscountcode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := subscriptiondiscountcode.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionDiscountCodeCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "SubscriptionDiscountCode.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := subscriptiondiscountcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDiscountCode.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DiscountType(); !ok {
		return &ValidationError{Name: "discount_type", err: errors.New(`ent: missing required field "SubscriptionDiscountCode.discount_type"`)}
	}
	if v, ok := _c.mutation.DiscountType(); ok {
		if err := subscriptiondiscountcode.DiscountTypeValidator(v); err != nil {
			return &ValidationError{Name: "discount_type", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDiscountCode.discount_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DiscountValue(); !ok {
		return &ValidationError{Name: "discount_value", err: errors.New(`ent: missing required field "SubscriptionDiscountCode.discount_value"`)}
	}
	if _, ok := _c.mutation.PlanIds(); !ok {
		return &ValidationError{Name: "plan_ids", err: errors.New(`ent: missing required field "SubscriptionDiscountCode.plan_ids"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "SubscriptionDiscountCode.enabled"`)}
	}
	if _, ok := _c.mutation.MaxUses(); !ok {
		return &ValidationError{Name: "max_uses", err: errors.New(`ent: missing required field "SubscriptionDiscountCode.max_uses"`)}
	}
	if v, ok := _c.mutation.MaxUses(); ok {
		if err := subscriptiondiscountcode.MaxUsesValidator(v); err != nil {
			return &ValidationError{Name: "max_uses", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDiscountCode.max_uses": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PerUserLimit(); !ok {
		return &ValidationError{Name: "per_user_limit", err: errors.New(`ent: missing required field "SubscriptionDiscountCode.per_user_limit"`)}
	}
	if v, ok := _c.mutation.PerUserLimit(); ok {
		if err := subscriptiondiscountcode.PerUserLimitValidator(v); err != nil {
			return &ValidationError{Name: "per_user_limit", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDiscountCode.per_user_limit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionDiscountCode.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubscriptionDiscountCode.updated_at"`)}
	}
	return nil
}

func (_c *SubscriptionDiscountCodeCreate) sqlSave(ctx context.Context) (*SubscriptionDiscountCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionDiscountCodeCreate) createSpec() (*SubscriptionDiscountCode, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionDiscountCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptiondiscountcode.Table, sqlgraph.NewFieldSpec(subscriptiondiscountcode.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.DiscountType(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldDiscountType, field.TypeString, value)
		_node.DiscountType = value
	}
	if value, ok := _c.mutation.DiscountValue(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldDiscountValue, field.TypeFloat64, value)
		_node.DiscountValue = value
	}
	if value, ok := _c.mutation.PlanIds(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldPlanIds, field.TypeJSON, value)
		_node.PlanIds = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.MaxUses(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldMaxUses, field.TypeInt, value)
		_node.MaxUses = value
	}
	if value, ok := _c.mutation.PerUserLimit(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldPerUserLimit, field.TypeInt, value)
		_node.PerUserLimit = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptiondiscountcode.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionDiscountCode.Create().
//		SetCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionDiscountCodeUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionDiscountCodeCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionDiscountCodeUpsertOne {
	_c.conflict = opts
	return &SubscriptionDiscountCodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionDiscountCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionDiscountCodeCreate) OnConflictColumns(columns ...string) *SubscriptionDiscountCodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionDiscountCodeUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionDiscountCodeUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionDiscountCode node.
	SubscriptionDiscountCodeUpsertOne struct {
		create *SubscriptionDiscountCodeCreate
	}

	// SubscriptionDiscountCodeUpsert is the "OnConflict" setter.
	SubscriptionDiscountCodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetDiscountType sets the "discount_type" field.
func (u *SubscriptionDiscountCodeUpsert) SetDiscountType(v string) *SubscriptionDiscountCodeUpsert {
	u.Set(subscriptiondiscountcode.FieldDiscountType, v)
	return u
}

// UpdateDiscountType sets the "discount_type" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsert) UpdateDiscountType() *SubscriptionDiscountCodeUpsert {
	u.SetExcluded(subscriptiondiscountcode.FieldDiscountType)
	return u
}

// SetDiscountValue sets the "discount_value" field.
func (u *SubscriptionDiscountCodeUpsert) SetDiscountValue(v float64) *SubscriptionDiscountCodeUpsert {
	u.Set(subscriptiondiscountcode.FieldDiscountValue, v)
	return u
}

// UpdateDiscountValue sets the "discount_value" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsert) UpdateDiscountValue() *SubscriptionDiscountCodeUpsert {
	u.SetExcluded(subscriptiondiscountcode.FieldDiscountValue)
	return u
}

// AddDiscountValue adds v to the "discount_value" field.
func (u *SubscriptionDiscountCodeUpsert) AddDiscountValue(v float64) *SubscriptionDiscountCodeUpsert {
	u.Add(subscriptiondiscountcode.FieldDiscountValue, v)
	return u
}

// SetPlanIds sets the "plan_ids" field.
func (u *SubscriptionDiscountCodeUpsert) SetPlanIds(v []int64) *SubscriptionDiscountCodeUpsert {
	u.Set(subscriptiondiscountcode.FieldPlanIds, v)
	return u
}

// UpdatePlanIds sets the "plan_ids" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsert) UpdatePlanIds() *SubscriptionDiscountCodeUpsert {
	u.SetExcluded(subscriptiondiscountcode.FieldPlanIds)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *SubscriptionDiscountCodeUpsert) SetEnabled(v bool) *SubscriptionDiscountCodeUpsert {
	u.Set(subscriptiondiscountcode.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsert) UpdateEnabled() *SubscriptionDiscountCodeUpsert {
	u.SetExcluded(subscriptiondiscountcode.FieldEnabled)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionDiscountCodeUpsert) SetExpiresAt(v time.Time) *SubscriptionDiscountCodeUpsert {
	u.Set(subscriptiondiscountcode.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsert) UpdateExpiresAt() *SubscriptionDiscountCodeUpsert {
	u.SetExcluded(subscriptiondiscountcode.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *SubscriptionDiscountCodeUpsert) ClearExpiresAt() *SubscriptionDiscountCodeUpsert {
	u.SetNull(subscriptiondiscountcode.FieldExpiresAt)
	return u
}

// SetMaxUses sets the "max_uses" field.
func (u *SubscriptionDiscountCodeUpsert) SetMaxUses(v int) *SubscriptionDiscountCodeUpsert {
	u.Set(subscriptiondiscountcode.FieldMaxUses, v)
	return u
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsert) UpdateMaxUses() *SubscriptionDiscountCodeUpsert {
	u.SetExcluded(subscriptiondiscountcode.FieldMaxUses)
	return u
}

// AddMaxUses adds v to the "max_uses" field.
func (u *SubscriptionDiscountCodeUpsert) AddMaxUses(v int) *SubscriptionDiscountCodeUpsert {
	u.Add(subscriptiondiscountcode.FieldMaxUses, v)
	return u
}

// SetPerUserLimit sets the "per_user_limit" field.
func (u *SubscriptionDiscountCodeUpsert) SetPerUserLimit(v int) *SubscriptionDiscountCodeUpsert {
	u.Set(subscriptiondiscountcode.FieldPerUserLimit, v)
	return u
}

// UpdatePerUserLimit sets the "per_user_limit" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsert) UpdatePerUserLimit() *SubscriptionDiscountCodeUpsert {
	u.SetExcluded(subscriptiondiscountcode.FieldPerUserLimit)
	return u
}

// AddPerUserLimit adds v to the "per_user_limit" field.
func (u *SubscriptionDiscountCodeUpsert) AddPerUserLimit(v int) *SubscriptionDiscountCodeUpsert {
	u.Add(subscriptiondiscountcode.FieldPerUserLimit, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionDiscountCodeUpsert) SetUpdatedAt(v time.Time) *SubscriptionDiscountCodeUpsert {
	u.Set(subscriptiondiscountcode.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsert) UpdateUpdatedAt() *SubscriptionDiscountCodeUpsert {
	u.SetExcluded(subscriptiondiscountcode.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionDiscountCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionDiscountCodeUpsertOne) UpdateNewValues() *SubscriptionDiscountCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.Code(); exists {
			s.SetIgnore(subscriptiondiscountcode.FieldCode)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptiondiscountcode.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionDiscountCode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionDiscountCodeUpsertOne) Ignore() *SubscriptionDiscountCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionDiscountCodeUpsertOne) DoNothing() *SubscriptionDiscountCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionDiscountCodeCreate.OnConflict
// documentation for more info.
func (u *SubscriptionDiscountCodeUpsertOne) Update(set func(*SubscriptionDiscountCodeUpsert)) *SubscriptionDiscountCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionDiscountCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetDiscountType sets the "discount_type" field.
func (u *SubscriptionDiscountCodeUpsertOne) SetDiscountType(v string) *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.SetDiscountType(v)
	})
}

// UpdateDiscountType sets the "discount_type" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsertOne) UpdateDiscountType() *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.UpdateDiscountType()
	})
}

// SetDiscountValue sets the "discount_value" field.
func (u *SubscriptionDiscountCodeUpsertOne) SetDiscountValue(v float64) *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.SetDiscountValue(v)
	})
}

// AddDiscountValue adds v to the "discount_value" field.
func (u *SubscriptionDiscountCodeUpsertOne) AddDiscountValue(v float64) *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.AddDiscountValue(v)
	})
}

// UpdateDiscountValue sets the "discount_value" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsertOne) UpdateDiscountValue() *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.UpdateDiscountValue()
	})
}

// SetPlanIds sets the "plan_ids" field.
func (u *SubscriptionDiscountCodeUpsertOne) SetPlanIds(v []int64) *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.SetPlanIds(v)
	})
}

// UpdatePlanIds sets the "plan_ids" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsertOne) UpdatePlanIds() *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.UpdatePlanIds()
	})
}

// SetEnabled sets the "enabled" field.
func (u *SubscriptionDiscountCodeUpsertOne) SetEnabled(v bool) *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsertOne) UpdateEnabled() *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.UpdateEnabled()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionDiscountCodeUpsertOne) SetExpiresAt(v time.Time) *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsertOne) UpdateExpiresAt() *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *SubscriptionDiscountCodeUpsertOne) ClearExpiresAt() *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.ClearExpiresAt()
	})
}

// SetMaxUses sets the "max_uses" field.
func (u *SubscriptionDiscountCodeUpsertOne) SetMaxUses(v int) *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.SetMaxUses(v)
	})
}

// AddMaxUses adds v to the "max_uses" field.
func (u *SubscriptionDiscountCodeUpsertOne) AddMaxUses(v int) *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.AddMaxUses(v)
	})
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsertOne) UpdateMaxUses() *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.UpdateMaxUses()
	})
}

// SetPerUserLimit sets the "per_user_limit" field.
func (u *SubscriptionDiscountCodeUpsertOne) SetPerUserLimit(v int) *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.SetPerUserLimit(v)
	})
}

// AddPerUserLimit adds v to the "per_user_limit" field.
func (u *SubscriptionDiscountCodeUpsertOne) AddPerUserLimit(v int) *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.AddPerUserLimit(v)
	})
}

// UpdatePerUserLimit sets the "per_user_limit" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsertOne) UpdatePerUserLimit() *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.UpdatePerUserLimit()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionDiscountCodeUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsertOne) UpdateUpdatedAt() *SubscriptionDiscountCodeUpsertOne {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SubscriptionDiscountCodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionDiscountCodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionDiscountCodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionDiscountCodeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionDiscountCodeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionDiscountCodeCreateBulk is the builder for creating many SubscriptionDiscountCode entities in bulk.
type SubscriptionDiscountCodeCreateBulk struct {
	config
	err      error
	builders []*SubscriptionDiscountCodeCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionDiscountCode entities in the database.
func (_c *SubscriptionDiscountCodeCreateBulk) Save(ctx context.Context) ([]*SubscriptionDiscountCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionDiscountCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionDiscountCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionDiscountCodeCreateBulk) SaveX(ctx context.Context) []*SubscriptionDiscountCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionDiscountCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionDiscountCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionDiscountCode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionDiscountCodeUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionDiscountCodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionDiscountCodeUpsertBulk {
	_c.conflict = opts
	return &SubscriptionDiscountCodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionDiscountCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionDiscountCodeCreateBulk) OnConflictColumns(columns ...string) *SubscriptionDiscountCodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionDiscountCodeUpsertBulk{
		create: _c,
	}
}

// SubscriptionDiscountCodeUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionDiscountCode nodes.
type SubscriptionDiscountCodeUpsertBulk struct {
	create *SubscriptionDiscountCodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionDiscountCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionDiscountCodeUpsertBulk) UpdateNewValues() *SubscriptionDiscountCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.Code(); exists {
				s.SetIgnore(subscriptiondiscountcode.FieldCode)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptiondiscountcode.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionDiscountCode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionDiscountCodeUpsertBulk) Ignore() *SubscriptionDiscountCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionDiscountCodeUpsertBulk) DoNothing() *SubscriptionDiscountCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionDiscountCodeCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionDiscountCodeUpsertBulk) Update(set func(*SubscriptionDiscountCodeUpsert)) *SubscriptionDiscountCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionDiscountCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetDiscountType sets the "discount_type" field.
func (u *SubscriptionDiscountCodeUpsertBulk) SetDiscountType(v string) *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.SetDiscountType(v)
	})
}

// UpdateDiscountType sets the "discount_type" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsertBulk) UpdateDiscountType() *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.UpdateDiscountType()
	})
}

// SetDiscountValue sets the "discount_value" field.
func (u *SubscriptionDiscountCodeUpsertBulk) SetDiscountValue(v float64) *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.SetDiscountValue(v)
	})
}

// AddDiscountValue adds v to the "discount_value" field.
func (u *SubscriptionDiscountCodeUpsertBulk) AddDiscountValue(v float64) *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.AddDiscountValue(v)
	})
}

// UpdateDiscountValue sets the "discount_value" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsertBulk) UpdateDiscountValue() *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.UpdateDiscountValue()
	})
}

// SetPlanIds sets the "plan_ids" field.
func (u *SubscriptionDiscountCodeUpsertBulk) SetPlanIds(v []int64) *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.SetPlanIds(v)
	})
}

// UpdatePlanIds sets the "plan_ids" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsertBulk) UpdatePlanIds() *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.UpdatePlanIds()
	})
}

// SetEnabled sets the "enabled" field.
func (u *SubscriptionDiscountCodeUpsertBulk) SetEnabled(v bool) *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsertBulk) UpdateEnabled() *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.UpdateEnabled()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubscriptionDiscountCodeUpsertBulk) SetExpiresAt(v time.Time) *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsertBulk) UpdateExpiresAt() *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *SubscriptionDiscountCodeUpsertBulk) ClearExpiresAt() *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.ClearExpiresAt()
	})
}

// SetMaxUses sets the "max_uses" field.
func (u *SubscriptionDiscountCodeUpsertBulk) SetMaxUses(v int) *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.SetMaxUses(v)
	})
}

// AddMaxUses adds v to the "max_uses" field.
func (u *SubscriptionDiscountCodeUpsertBulk) AddMaxUses(v int) *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.AddMaxUses(v)
	})
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsertBulk) UpdateMaxUses() *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.UpdateMaxUses()
	})
}

// SetPerUserLimit sets the "per_user_limit" field.
func (u *SubscriptionDiscountCodeUpsertBulk) SetPerUserLimit(v int) *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.SetPerUserLimit(v)
	})
}

// AddPerUserLimit adds v to the "per_user_limit" field.
func (u *SubscriptionDiscountCodeUpsertBulk) AddPerUserLimit(v int) *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.AddPerUserLimit(v)
	})
}

// UpdatePerUserLimit sets the "per_user_limit" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsertBulk) UpdatePerUserLimit() *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.UpdatePerUserLimit()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionDiscountCodeUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionDiscountCodeUpsertBulk) UpdateUpdatedAt() *SubscriptionDiscountCodeUpsertBulk {
	return u.Update(func(s *SubscriptionDiscountCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SubscriptionDiscountCodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionDiscountCodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionDiscountCodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionDiscountCodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
