// Code generated by ent, DO NOT EDIT.

package invoicerequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the invoicerequest type in the database.
	Label = "invoice_request"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTaxID holds the string denoting the tax_id field in the database.
	FieldTaxID = "tax_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldRemarks holds the string denoting the remarks field in the database.
	FieldRemarks = "remarks"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldBaseAmount holds the string denoting the base_amount field in the database.
	FieldBaseAmount = "base_amount"
	// FieldServiceFee holds the string denoting the service_fee field in the database.
	FieldServiceFee = "service_fee"
	// FieldTotalAmount holds the string denoting the total_amount field in the database.
	FieldTotalAmount = "total_amount"
	// FieldNetAmount holds the string denoting the net_amount field in the database.
	FieldNetAmount = "net_amount"
	// FieldTaxAmount holds the string denoting the tax_amount field in the database.
	FieldTaxAmount = "tax_amount"
	// FieldItemName holds the string denoting the item_name field in the database.
	FieldItemName = "item_name"
	// FieldTaxRate holds the string denoting the tax_rate field in the database.
	FieldTaxRate = "tax_rate"
	// FieldFeeType holds the string denoting the fee_type field in the database.
	FieldFeeType = "fee_type"
	// FieldFeeValue holds the string denoting the fee_value field in the database.
	FieldFeeValue = "fee_value"
	// FieldFeeUpperAmount holds the string denoting the fee_upper_amount field in the database.
	FieldFeeUpperAmount = "fee_upper_amount"
	// FieldOperationKey holds the string denoting the operation_key field in the database.
	FieldOperationKey = "operation_key"
	// FieldFingerprint holds the string denoting the fingerprint field in the database.
	FieldFingerprint = "fingerprint"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldSubmittedAt holds the string denoting the submitted_at field in the database.
	FieldSubmittedAt = "submitted_at"
	// FieldIssuedAt holds the string denoting the issued_at field in the database.
	FieldIssuedAt = "issued_at"
	// FieldIssuedBy holds the string denoting the issued_by field in the database.
	FieldIssuedBy = "issued_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the invoicerequest in the database.
	Table = "invoice_requests"
)

// Columns holds all SQL columns for invoicerequest fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldStatus,
	FieldTaxID,
	FieldTitle,
	FieldEmail,
	FieldRemarks,
	FieldCurrency,
	FieldBaseAmount,
	FieldServiceFee,
	FieldTotalAmount,
	FieldNetAmount,
	FieldTaxAmount,
	FieldItemName,
	FieldTaxRate,
	FieldFeeType,
	FieldFeeValue,
	FieldFeeUpperAmount,
	FieldOperationKey,
	FieldFingerprint,
	FieldExpiresAt,
	FieldSubmittedAt,
	FieldIssuedAt,
	FieldIssuedBy,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// TaxIDValidator is a validator for the "tax_id" field. It is called by the builders before save.
	TaxIDValidator func(string) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultRemarks holds the default value on creation for the "remarks" field.
	DefaultRemarks string
	// RemarksValidator is a validator for the "remarks" field. It is called by the builders before save.
	RemarksValidator func(string) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// ItemNameValidator is a validator for the "item_name" field. It is called by the builders before save.
	ItemNameValidator func(string) error
	// FeeTypeValidator is a validator for the "fee_type" field. It is called by the builders before save.
	FeeTypeValidator func(string) error
	// OperationKeyValidator is a validator for the "operation_key" field. It is called by the builders before save.
	OperationKeyValidator func(string) error
	// FingerprintValidator is a validator for the "fingerprint" field. It is called by the builders before save.
	FingerprintValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the InvoiceRequest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTaxID orders the results by the tax_id field.
func ByTaxID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByRemarks orders the results by the remarks field.
func ByRemarks(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemarks, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByBaseAmount orders the results by the base_amount field.
func ByBaseAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseAmount, opts...).ToFunc()
}

// ByServiceFee orders the results by the service_fee field.
func ByServiceFee(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceFee, opts...).ToFunc()
}

// ByTotalAmount orders the results by the total_amount field.
func ByTotalAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalAmount, opts...).ToFunc()
}

// ByNetAmount orders the results by the net_amount field.
func ByNetAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNetAmount, opts...).ToFunc()
}

// ByTaxAmount orders the results by the tax_amount field.
func ByTaxAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxAmount, opts...).ToFunc()
}

// ByItemName orders the results by the item_name field.
func ByItemName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemName, opts...).ToFunc()
}

// ByTaxRate orders the results by the tax_rate field.
func ByTaxRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxRate, opts...).ToFunc()
}

// ByFeeType orders the results by the fee_type field.
func ByFeeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeType, opts...).ToFunc()
}

// ByFeeValue orders the results by the fee_value field.
func ByFeeValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeValue, opts...).ToFunc()
}

// ByFeeUpperAmount orders the results by the fee_upper_amount field.
func ByFeeUpperAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeUpperAmount, opts...).ToFunc()
}

// ByOperationKey orders the results by the operation_key field.
func ByOperationKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperationKey, opts...).ToFunc()
}

// ByFingerprint orders the results by the fingerprint field.
func ByFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFingerprint, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// BySubmittedAt orders the results by the submitted_at field.
func BySubmittedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmittedAt, opts...).ToFunc()
}

// ByIssuedAt orders the results by the issued_at field.
func ByIssuedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuedAt, opts...).ToFunc()
}

// ByIssuedBy orders the results by the issued_by field.
func ByIssuedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
