// Code generated by ent, DO NOT EDIT.

package invoicerequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUserID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldStatus, v))
}

// TaxID applies equality check predicate on the "tax_id" field. It's identical to TaxIDEQ.
func TaxID(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTaxID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTitle, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldEmail, v))
}

// Remarks applies equality check predicate on the "remarks" field. It's identical to RemarksEQ.
func Remarks(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldRemarks, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldCurrency, v))
}

// BaseAmount applies equality check predicate on the "base_amount" field. It's identical to BaseAmountEQ.
func BaseAmount(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldBaseAmount, v))
}

// ServiceFee applies equality check predicate on the "service_fee" field. It's identical to ServiceFeeEQ.
func ServiceFee(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldServiceFee, v))
}

// TotalAmount applies equality check predicate on the "total_amount" field. It's identical to TotalAmountEQ.
func TotalAmount(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTotalAmount, v))
}

// NetAmount applies equality check predicate on the "net_amount" field. It's identical to NetAmountEQ.
func NetAmount(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldNetAmount, v))
}

// TaxAmount applies equality check predicate on the "tax_amount" field. It's identical to TaxAmountEQ.
func TaxAmount(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTaxAmount, v))
}

// ItemName applies equality check predicate on the "item_name" field. It's identical to ItemNameEQ.
func ItemName(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldItemName, v))
}

// TaxRate applies equality check predicate on the "tax_rate" field. It's identical to TaxRateEQ.
func TaxRate(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTaxRate, v))
}

// FeeType applies equality check predicate on the "fee_type" field. It's identical to FeeTypeEQ.
func FeeType(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldFeeType, v))
}

// FeeValue applies equality check predicate on the "fee_value" field. It's identical to FeeValueEQ.
func FeeValue(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldFeeValue, v))
}

// FeeUpperAmount applies equality check predicate on the "fee_upper_amount" field. It's identical to FeeUpperAmountEQ.
func FeeUpperAmount(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldFeeUpperAmount, v))
}

// OperationKey applies equality check predicate on the "operation_key" field. It's identical to OperationKeyEQ.
func OperationKey(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldOperationKey, v))
}

// Fingerprint applies equality check predicate on the "fingerprint" field. It's identical to FingerprintEQ.
func Fingerprint(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldFingerprint, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldExpiresAt, v))
}

// SubmittedAt applies equality check predicate on the "submitted_at" field. It's identical to SubmittedAtEQ.
func SubmittedAt(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldSubmittedAt, v))
}

// IssuedAt applies equality check predicate on the "issued_at" field. It's identical to IssuedAtEQ.
func IssuedAt(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldIssuedAt, v))
}

// IssuedBy applies equality check predicate on the "issued_by" field. It's identical to IssuedByEQ.
func IssuedBy(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldIssuedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldUserID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldStatus, v))
}

// TaxIDEQ applies the EQ predicate on the "tax_id" field.
func TaxIDEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTaxID, v))
}

// TaxIDNEQ applies the NEQ predicate on the "tax_id" field.
func TaxIDNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldTaxID, v))
}

// TaxIDIn applies the In predicate on the "tax_id" field.
func TaxIDIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldTaxID, vs...))
}

// TaxIDNotIn applies the NotIn predicate on the "tax_id" field.
func TaxIDNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldTaxID, vs...))
}

// TaxIDGT applies the GT predicate on the "tax_id" field.
func TaxIDGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldTaxID, v))
}

// TaxIDGTE applies the GTE predicate on the "tax_id" field.
func TaxIDGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldTaxID, v))
}

// TaxIDLT applies the LT predicate on the "tax_id" field.
func TaxIDLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldTaxID, v))
}

// TaxIDLTE applies the LTE predicate on the "tax_id" field.
func TaxIDLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldTaxID, v))
}

// TaxIDContains applies the Contains predicate on the "tax_id" field.
func TaxIDContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldTaxID, v))
}

// TaxIDHasPrefix applies the HasPrefix predicate on the "tax_id" field.
func TaxIDHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldTaxID, v))
}

// TaxIDHasSuffix applies the HasSuffix predicate on the "tax_id" field.
func TaxIDHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldTaxID, v))
}

// TaxIDEqualFold applies the EqualFold predicate on the "tax_id" field.
func TaxIDEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldTaxID, v))
}

// TaxIDContainsFold applies the ContainsFold predicate on the "tax_id" field.
func TaxIDContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldTaxID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldTitle, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldEmail, v))
}

// RemarksEQ applies the EQ predicate on the "remarks" field.
func RemarksEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldRemarks, v))
}

// RemarksNEQ applies the NEQ predicate on the "remarks" field.
func RemarksNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldRemarks, v))
}

// RemarksIn applies the In predicate on the "remarks" field.
func RemarksIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldRemarks, vs...))
}

// RemarksNotIn applies the NotIn predicate on the "remarks" field.
func RemarksNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldRemarks, vs...))
}

// RemarksGT applies the GT predicate on the "remarks" field.
func RemarksGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldRemarks, v))
}

// RemarksGTE applies the GTE predicate on the "remarks" field.
func RemarksGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldRemarks, v))
}

// RemarksLT applies the LT predicate on the "remarks" field.
func RemarksLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldRemarks, v))
}

// RemarksLTE applies the LTE predicate on the "remarks" field.
func RemarksLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldRemarks, v))
}

// RemarksContains applies the Contains predicate on the "remarks" field.
func RemarksContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldRemarks, v))
}

// RemarksHasPrefix applies the HasPrefix predicate on the "remarks" field.
func RemarksHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldRemarks, v))
}

// RemarksHasSuffix applies the HasSuffix predicate on the "remarks" field.
func RemarksHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldRemarks, v))
}

// RemarksEqualFold applies the EqualFold predicate on the "remarks" field.
func RemarksEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldRemarks, v))
}

// RemarksContainsFold applies the ContainsFold predicate on the "remarks" field.
func RemarksContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldRemarks, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldCurrency, v))
}

// BaseAmountEQ applies the EQ predicate on the "base_amount" field.
func BaseAmountEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldBaseAmount, v))
}

// BaseAmountNEQ applies the NEQ predicate on the "base_amount" field.
func BaseAmountNEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldBaseAmount, v))
}

// BaseAmountIn applies the In predicate on the "base_amount" field.
func BaseAmountIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldBaseAmount, vs...))
}

// BaseAmountNotIn applies the NotIn predicate on the "base_amount" field.
func BaseAmountNotIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldBaseAmount, vs...))
}

// BaseAmountGT applies the GT predicate on the "base_amount" field.
func BaseAmountGT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldBaseAmount, v))
}

// BaseAmountGTE applies the GTE predicate on the "base_amount" field.
func BaseAmountGTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldBaseAmount, v))
}

// BaseAmountLT applies the LT predicate on the "base_amount" field.
func BaseAmountLT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldBaseAmount, v))
}

// BaseAmountLTE applies the LTE predicate on the "base_amount" field.
func BaseAmountLTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldBaseAmount, v))
}

// ServiceFeeEQ applies the EQ predicate on the "service_fee" field.
func ServiceFeeEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldServiceFee, v))
}

// ServiceFeeNEQ applies the NEQ predicate on the "service_fee" field.
func ServiceFeeNEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldServiceFee, v))
}

// ServiceFeeIn applies the In predicate on the "service_fee" field.
func ServiceFeeIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldServiceFee, vs...))
}

// ServiceFeeNotIn applies the NotIn predicate on the "service_fee" field.
func ServiceFeeNotIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldServiceFee, vs...))
}

// ServiceFeeGT applies the GT predicate on the "service_fee" field.
func ServiceFeeGT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldServiceFee, v))
}

// ServiceFeeGTE applies the GTE predicate on the "service_fee" field.
func ServiceFeeGTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldServiceFee, v))
}

// ServiceFeeLT applies the LT predicate on the "service_fee" field.
func ServiceFeeLT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldServiceFee, v))
}

// ServiceFeeLTE applies the LTE predicate on the "service_fee" field.
func ServiceFeeLTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldServiceFee, v))
}

// TotalAmountEQ applies the EQ predicate on the "total_amount" field.
func TotalAmountEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTotalAmount, v))
}

// TotalAmountNEQ applies the NEQ predicate on the "total_amount" field.
func TotalAmountNEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldTotalAmount, v))
}

// TotalAmountIn applies the In predicate on the "total_amount" field.
func TotalAmountIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldTotalAmount, vs...))
}

// TotalAmountNotIn applies the NotIn predicate on the "total_amount" field.
func TotalAmountNotIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldTotalAmount, vs...))
}

// TotalAmountGT applies the GT predicate on the "total_amount" field.
func TotalAmountGT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldTotalAmount, v))
}

// TotalAmountGTE applies the GTE predicate on the "total_amount" field.
func TotalAmountGTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldTotalAmount, v))
}

// TotalAmountLT applies the LT predicate on the "total_amount" field.
func TotalAmountLT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldTotalAmount, v))
}

// TotalAmountLTE applies the LTE predicate on the "total_amount" field.
func TotalAmountLTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldTotalAmount, v))
}

// NetAmountEQ applies the EQ predicate on the "net_amount" field.
func NetAmountEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldNetAmount, v))
}

// NetAmountNEQ applies the NEQ predicate on the "net_amount" field.
func NetAmountNEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldNetAmount, v))
}

// NetAmountIn applies the In predicate on the "net_amount" field.
func NetAmountIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldNetAmount, vs...))
}

// NetAmountNotIn applies the NotIn predicate on the "net_amount" field.
func NetAmountNotIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldNetAmount, vs...))
}

// NetAmountGT applies the GT predicate on the "net_amount" field.
func NetAmountGT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldNetAmount, v))
}

// NetAmountGTE applies the GTE predicate on the "net_amount" field.
func NetAmountGTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldNetAmount, v))
}

// NetAmountLT applies the LT predicate on the "net_amount" field.
func NetAmountLT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldNetAmount, v))
}

// NetAmountLTE applies the LTE predicate on the "net_amount" field.
func NetAmountLTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldNetAmount, v))
}

// TaxAmountEQ applies the EQ predicate on the "tax_amount" field.
func TaxAmountEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTaxAmount, v))
}

// TaxAmountNEQ applies the NEQ predicate on the "tax_amount" field.
func TaxAmountNEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldTaxAmount, v))
}

// TaxAmountIn applies the In predicate on the "tax_amount" field.
func TaxAmountIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldTaxAmount, vs...))
}

// TaxAmountNotIn applies the NotIn predicate on the "tax_amount" field.
func TaxAmountNotIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldTaxAmount, vs...))
}

// TaxAmountGT applies the GT predicate on the "tax_amount" field.
func TaxAmountGT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldTaxAmount, v))
}

// TaxAmountGTE applies the GTE predicate on the "tax_amount" field.
func TaxAmountGTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldTaxAmount, v))
}

// TaxAmountLT applies the LT predicate on the "tax_amount" field.
func TaxAmountLT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldTaxAmount, v))
}

// TaxAmountLTE applies the LTE predicate on the "tax_amount" field.
func TaxAmountLTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldTaxAmount, v))
}

// ItemNameEQ applies the EQ predicate on the "item_name" field.
func ItemNameEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldItemName, v))
}

// ItemNameNEQ applies the NEQ predicate on the "item_name" field.
func ItemNameNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldItemName, v))
}

// ItemNameIn applies the In predicate on the "item_name" field.
func ItemNameIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldItemName, vs...))
}

// ItemNameNotIn applies the NotIn predicate on the "item_name" field.
func ItemNameNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldItemName, vs...))
}

// ItemNameGT applies the GT predicate on the "item_name" field.
func ItemNameGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldItemName, v))
}

// ItemNameGTE applies the GTE predicate on the "item_name" field.
func ItemNameGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldItemName, v))
}

// ItemNameLT applies the LT predicate on the "item_name" field.
func ItemNameLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldItemName, v))
}

// ItemNameLTE applies the LTE predicate on the "item_name" field.
func ItemNameLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldItemName, v))
}

// ItemNameContains applies the Contains predicate on the "item_name" field.
func ItemNameContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldItemName, v))
}

// ItemNameHasPrefix applies the HasPrefix predicate on the "item_name" field.
func ItemNameHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldItemName, v))
}

// ItemNameHasSuffix applies the HasSuffix predicate on the "item_name" field.
func ItemNameHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldItemName, v))
}

// ItemNameEqualFold applies the EqualFold predicate on the "item_name" field.
func ItemNameEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldItemName, v))
}

// ItemNameContainsFold applies the ContainsFold predicate on the "item_name" field.
func ItemNameContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldItemName, v))
}

// TaxRateEQ applies the EQ predicate on the "tax_rate" field.
func TaxRateEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTaxRate, v))
}

// TaxRateNEQ applies the NEQ predicate on the "tax_rate" field.
func TaxRateNEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldTaxRate, v))
}

// TaxRateIn applies the In predicate on the "tax_rate" field.
func TaxRateIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldTaxRate, vs...))
}

// TaxRateNotIn applies the NotIn predicate on the "tax_rate" field.
func TaxRateNotIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldTaxRate, vs...))
}

// TaxRateGT applies the GT predicate on the "tax_rate" field.
func TaxRateGT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldTaxRate, v))
}

// TaxRateGTE applies the GTE predicate on the "tax_rate" field.
func TaxRateGTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldTaxRate, v))
}

// TaxRateLT applies the LT predicate on the "tax_rate" field.
func TaxRateLT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldTaxRate, v))
}

// TaxRateLTE applies the LTE predicate on the "tax_rate" field.
func TaxRateLTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldTaxRate, v))
}

// FeeTypeEQ applies the EQ predicate on the "fee_type" field.
func FeeTypeEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldFeeType, v))
}

// FeeTypeNEQ applies the NEQ predicate on the "fee_type" field.
func FeeTypeNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldFeeType, v))
}

// FeeTypeIn applies the In predicate on the "fee_type" field.
func FeeTypeIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldFeeType, vs...))
}

// FeeTypeNotIn applies the NotIn predicate on the "fee_type" field.
func FeeTypeNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldFeeType, vs...))
}

// FeeTypeGT applies the GT predicate on the "fee_type" field.
func FeeTypeGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldFeeType, v))
}

// FeeTypeGTE applies the GTE predicate on the "fee_type" field.
func FeeTypeGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldFeeType, v))
}

// FeeTypeLT applies the LT predicate on the "fee_type" field.
func FeeTypeLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldFeeType, v))
}

// FeeTypeLTE applies the LTE predicate on the "fee_type" field.
func FeeTypeLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldFeeType, v))
}

// FeeTypeContains applies the Contains predicate on the "fee_type" field.
func FeeTypeContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldFeeType, v))
}

// FeeTypeHasPrefix applies the HasPrefix predicate on the "fee_type" field.
func FeeTypeHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldFeeType, v))
}

// FeeTypeHasSuffix applies the HasSuffix predicate on the "fee_type" field.
func FeeTypeHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldFeeType, v))
}

// FeeTypeEqualFold applies the EqualFold predicate on the "fee_type" field.
func FeeTypeEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldFeeType, v))
}

// FeeTypeContainsFold applies the ContainsFold predicate on the "fee_type" field.
func FeeTypeContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldFeeType, v))
}

// FeeValueEQ applies the EQ predicate on the "fee_value" field.
func FeeValueEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldFeeValue, v))
}

// FeeValueNEQ applies the NEQ predicate on the "fee_value" field.
func FeeValueNEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldFeeValue, v))
}

// FeeValueIn applies the In predicate on the "fee_value" field.
func FeeValueIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldFeeValue, vs...))
}

// FeeValueNotIn applies the NotIn predicate on the "fee_value" field.
func FeeValueNotIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldFeeValue, vs...))
}

// FeeValueGT applies the GT predicate on the "fee_value" field.
func FeeValueGT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldFeeValue, v))
}

// FeeValueGTE applies the GTE predicate on the "fee_value" field.
func FeeValueGTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldFeeValue, v))
}

// FeeValueLT applies the LT predicate on the "fee_value" field.
func FeeValueLT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldFeeValue, v))
}

// FeeValueLTE applies the LTE predicate on the "fee_value" field.
func FeeValueLTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldFeeValue, v))
}

// FeeUpperAmountEQ applies the EQ predicate on the "fee_upper_amount" field.
func FeeUpperAmountEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldFeeUpperAmount, v))
}

// FeeUpperAmountNEQ applies the NEQ predicate on the "fee_upper_amount" field.
func FeeUpperAmountNEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldFeeUpperAmount, v))
}

// FeeUpperAmountIn applies the In predicate on the "fee_upper_amount" field.
func FeeUpperAmountIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldFeeUpperAmount, vs...))
}

// FeeUpperAmountNotIn applies the NotIn predicate on the "fee_upper_amount" field.
func FeeUpperAmountNotIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldFeeUpperAmount, vs...))
}

// FeeUpperAmountGT applies the GT predicate on the "fee_upper_amount" field.
func FeeUpperAmountGT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldFeeUpperAmount, v))
}

// FeeUpperAmountGTE applies the GTE predicate on the "fee_upper_amount" field.
func FeeUpperAmountGTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldFeeUpperAmount, v))
}

// FeeUpperAmountLT applies the LT predicate on the "fee_upper_amount" field.
func FeeUpperAmountLT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldFeeUpperAmount, v))
}

// FeeUpperAmountLTE applies the LTE predicate on the "fee_upper_amount" field.
func FeeUpperAmountLTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldFeeUpperAmount, v))
}

// FeeUpperAmountIsNil applies the IsNil predicate on the "fee_upper_amount" field.
func FeeUpperAmountIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldFeeUpperAmount))
}

// FeeUpperAmountNotNil applies the NotNil predicate on the "fee_upper_amount" field.
func FeeUpperAmountNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldFeeUpperAmount))
}

// OperationKeyEQ applies the EQ predicate on the "operation_key" field.
func OperationKeyEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldOperationKey, v))
}

// OperationKeyNEQ applies the NEQ predicate on the "operation_key" field.
func OperationKeyNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldOperationKey, v))
}

// OperationKeyIn applies the In predicate on the "operation_key" field.
func OperationKeyIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldOperationKey, vs...))
}

// OperationKeyNotIn applies the NotIn predicate on the "operation_key" field.
func OperationKeyNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldOperationKey, vs...))
}

// OperationKeyGT applies the GT predicate on the "operation_key" field.
func OperationKeyGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldOperationKey, v))
}

// OperationKeyGTE applies the GTE predicate on the "operation_key" field.
func OperationKeyGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldOperationKey, v))
}

// OperationKeyLT applies the LT predicate on the "operation_key" field.
func OperationKeyLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldOperationKey, v))
}

// OperationKeyLTE applies the LTE predicate on the "operation_key" field.
func OperationKeyLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldOperationKey, v))
}

// OperationKeyContains applies the Contains predicate on the "operation_key" field.
func OperationKeyContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldOperationKey, v))
}

// OperationKeyHasPrefix applies the HasPrefix predicate on the "operation_key" field.
func OperationKeyHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldOperationKey, v))
}

// OperationKeyHasSuffix applies the HasSuffix predicate on the "operation_key" field.
func OperationKeyHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldOperationKey, v))
}

// OperationKeyEqualFold applies the EqualFold predicate on the "operation_key" field.
func OperationKeyEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldOperationKey, v))
}

// OperationKeyContainsFold applies the ContainsFold predicate on the "operation_key" field.
func OperationKeyContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldOperationKey, v))
}

// FingerprintEQ applies the EQ predicate on the "fingerprint" field.
func FingerprintEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldFingerprint, v))
}

// FingerprintNEQ applies the NEQ predicate on the "fingerprint" field.
func FingerprintNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldFingerprint, v))
}

// FingerprintIn applies the In predicate on the "fingerprint" field.
func FingerprintIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldFingerprint, vs...))
}

// FingerprintNotIn applies the NotIn predicate on the "fingerprint" field.
func FingerprintNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldFingerprint, vs...))
}

// FingerprintGT applies the GT predicate on the "fingerprint" field.
func FingerprintGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldFingerprint, v))
}

// FingerprintGTE applies the GTE predicate on the "fingerprint" field.
func FingerprintGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldFingerprint, v))
}

// FingerprintLT applies the LT predicate on the "fingerprint" field.
func FingerprintLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldFingerprint, v))
}

// FingerprintLTE applies the LTE predicate on the "fingerprint" field.
func FingerprintLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldFingerprint, v))
}

// FingerprintContains applies the Contains predicate on the "fingerprint" field.
func FingerprintContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldFingerprint, v))
}

// FingerprintHasPrefix applies the HasPrefix predicate on the "fingerprint" field.
func FingerprintHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldFingerprint, v))
}

// FingerprintHasSuffix applies the HasSuffix predicate on the "fingerprint" field.
func FingerprintHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldFingerprint, v))
}

// FingerprintEqualFold applies the EqualFold predicate on the "fingerprint" field.
func FingerprintEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldFingerprint, v))
}

// FingerprintContainsFold applies the ContainsFold predicate on the "fingerprint" field.
func FingerprintContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldFingerprint, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldExpiresAt, v))
}

// SubmittedAtEQ applies the EQ predicate on the "submitted_at" field.
func SubmittedAtEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldSubmittedAt, v))
}

// SubmittedAtNEQ applies the NEQ predicate on the "submitted_at" field.
func SubmittedAtNEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldSubmittedAt, v))
}

// SubmittedAtIn applies the In predicate on the "submitted_at" field.
func SubmittedAtIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldSubmittedAt, vs...))
}

// SubmittedAtNotIn applies the NotIn predicate on the "submitted_at" field.
func SubmittedAtNotIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldSubmittedAt, vs...))
}

// SubmittedAtGT applies the GT predicate on the "submitted_at" field.
func SubmittedAtGT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldSubmittedAt, v))
}

// SubmittedAtGTE applies the GTE predicate on the "submitted_at" field.
func SubmittedAtGTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldSubmittedAt, v))
}

// SubmittedAtLT applies the LT predicate on the "submitted_at" field.
func SubmittedAtLT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldSubmittedAt, v))
}

// SubmittedAtLTE applies the LTE predicate on the "submitted_at" field.
func SubmittedAtLTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldSubmittedAt, v))
}

// SubmittedAtIsNil applies the IsNil predicate on the "submitted_at" field.
func SubmittedAtIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldSubmittedAt))
}

// SubmittedAtNotNil applies the NotNil predicate on the "submitted_at" field.
func SubmittedAtNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldSubmittedAt))
}

// IssuedAtEQ applies the EQ predicate on the "issued_at" field.
func IssuedAtEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldIssuedAt, v))
}

// IssuedAtNEQ applies the NEQ predicate on the "issued_at" field.
func IssuedAtNEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldIssuedAt, v))
}

// IssuedAtIn applies the In predicate on the "issued_at" field.
func IssuedAtIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldIssuedAt, vs...))
}

// IssuedAtNotIn applies the NotIn predicate on the "issued_at" field.
func IssuedAtNotIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldIssuedAt, vs...))
}

// IssuedAtGT applies the GT predicate on the "issued_at" field.
func IssuedAtGT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldIssuedAt, v))
}

// IssuedAtGTE applies the GTE predicate on the "issued_at" field.
func IssuedAtGTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldIssuedAt, v))
}

// IssuedAtLT applies the LT predicate on the "issued_at" field.
func IssuedAtLT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldIssuedAt, v))
}

// IssuedAtLTE applies the LTE predicate on the "issued_at" field.
func IssuedAtLTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldIssuedAt, v))
}

// IssuedAtIsNil applies the IsNil predicate on the "issued_at" field.
func IssuedAtIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldIssuedAt))
}

// IssuedAtNotNil applies the NotNil predicate on the "issued_at" field.
func IssuedAtNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldIssuedAt))
}

// IssuedByEQ applies the EQ predicate on the "issued_by" field.
func IssuedByEQ(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldIssuedBy, v))
}

// IssuedByNEQ applies the NEQ predicate on the "issued_by" field.
func IssuedByNEQ(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldIssuedBy, v))
}

// IssuedByIn applies the In predicate on the "issued_by" field.
func IssuedByIn(vs ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldIssuedBy, vs...))
}

// IssuedByNotIn applies the NotIn predicate on the "issued_by" field.
func IssuedByNotIn(vs ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldIssuedBy, vs...))
}

// IssuedByGT applies the GT predicate on the "issued_by" field.
func IssuedByGT(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldIssuedBy, v))
}

// IssuedByGTE applies the GTE predicate on the "issued_by" field.
func IssuedByGTE(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldIssuedBy, v))
}

// IssuedByLT applies the LT predicate on the "issued_by" field.
func IssuedByLT(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldIssuedBy, v))
}

// IssuedByLTE applies the LTE predicate on the "issued_by" field.
func IssuedByLTE(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldIssuedBy, v))
}

// IssuedByIsNil applies the IsNil predicate on the "issued_by" field.
func IssuedByIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldIssuedBy))
}

// IssuedByNotNil applies the NotNil predicate on the "issued_by" field.
func IssuedByNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldIssuedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceRequest) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceRequest) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceRequest) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.NotPredicates(p))
}
