// Code generated by ent, DO NOT EDIT.

package invitebinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the invitebinding type in the database.
	Label = "invite_binding"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInviterUserID holds the string denoting the inviter_user_id field in the database.
	FieldInviterUserID = "inviter_user_id"
	// FieldInviteeUserID holds the string denoting the invitee_user_id field in the database.
	FieldInviteeUserID = "invitee_user_id"
	// FieldInviteCodeID holds the string denoting the invite_code_id field in the database.
	FieldInviteCodeID = "invite_code_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeInviter holds the string denoting the inviter edge name in mutations.
	EdgeInviter = "inviter"
	// EdgeInvitee holds the string denoting the invitee edge name in mutations.
	EdgeInvitee = "invitee"
	// EdgeInviteCode holds the string denoting the invite_code edge name in mutations.
	EdgeInviteCode = "invite_code"
	// Table holds the table name of the invitebinding in the database.
	Table = "invite_bindings"
	// InviterTable is the table that holds the inviter relation/edge.
	InviterTable = "invite_bindings"
	// InviterInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	InviterInverseTable = "users"
	// InviterColumn is the table column denoting the inviter relation/edge.
	InviterColumn = "inviter_user_id"
	// InviteeTable is the table that holds the invitee relation/edge.
	InviteeTable = "invite_bindings"
	// InviteeInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	InviteeInverseTable = "users"
	// InviteeColumn is the table column denoting the invitee relation/edge.
	InviteeColumn = "invitee_user_id"
	// InviteCodeTable is the table that holds the invite_code relation/edge.
	InviteCodeTable = "invite_bindings"
	// InviteCodeInverseTable is the table name for the InviteCode entity.
	// It exists in this package in order to avoid circular dependency with the "invitecode" package.
	InviteCodeInverseTable = "invite_codes"
	// InviteCodeColumn is the table column denoting the invite_code relation/edge.
	InviteCodeColumn = "invite_code_id"
)

// Columns holds all SQL columns for invitebinding fields.
var Columns = []string{
	FieldID,
	FieldInviterUserID,
	FieldInviteeUserID,
	FieldInviteCodeID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the InviteBinding queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInviterUserID orders the results by the inviter_user_id field.
func ByInviterUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviterUserID, opts...).ToFunc()
}

// ByInviteeUserID orders the results by the invitee_user_id field.
func ByInviteeUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteeUserID, opts...).ToFunc()
}

// ByInviteCodeID orders the results by the invite_code_id field.
func ByInviteCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteCodeID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByInviterField orders the results by inviter field.
func ByInviterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInviterStep(), sql.OrderByField(field, opts...))
	}
}

// ByInviteeField orders the results by invitee field.
func ByInviteeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInviteeStep(), sql.OrderByField(field, opts...))
	}
}

// ByInviteCodeField orders the results by invite_code field.
func ByInviteCodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInviteCodeStep(), sql.OrderByField(field, opts...))
	}
}
func newInviterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InviterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InviterTable, InviterColumn),
	)
}
func newInviteeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InviteeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InviteeTable, InviteeColumn),
	)
}
func newInviteCodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InviteCodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InviteCodeTable, InviteCodeColumn),
	)
}
