// Code generated by ent, DO NOT EDIT.

package invitebinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldLTE(FieldID, id))
}

// InviterUserID applies equality check predicate on the "inviter_user_id" field. It's identical to InviterUserIDEQ.
func InviterUserID(v int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldEQ(FieldInviterUserID, v))
}

// InviteeUserID applies equality check predicate on the "invitee_user_id" field. It's identical to InviteeUserIDEQ.
func InviteeUserID(v int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldEQ(FieldInviteeUserID, v))
}

// InviteCodeID applies equality check predicate on the "invite_code_id" field. It's identical to InviteCodeIDEQ.
func InviteCodeID(v int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldEQ(FieldInviteCodeID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// InviterUserIDEQ applies the EQ predicate on the "inviter_user_id" field.
func InviterUserIDEQ(v int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldEQ(FieldInviterUserID, v))
}

// InviterUserIDNEQ applies the NEQ predicate on the "inviter_user_id" field.
func InviterUserIDNEQ(v int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldNEQ(FieldInviterUserID, v))
}

// InviterUserIDIn applies the In predicate on the "inviter_user_id" field.
func InviterUserIDIn(vs ...int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldIn(FieldInviterUserID, vs...))
}

// InviterUserIDNotIn applies the NotIn predicate on the "inviter_user_id" field.
func InviterUserIDNotIn(vs ...int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldNotIn(FieldInviterUserID, vs...))
}

// InviteeUserIDEQ applies the EQ predicate on the "invitee_user_id" field.
func InviteeUserIDEQ(v int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldEQ(FieldInviteeUserID, v))
}

// InviteeUserIDNEQ applies the NEQ predicate on the "invitee_user_id" field.
func InviteeUserIDNEQ(v int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldNEQ(FieldInviteeUserID, v))
}

// InviteeUserIDIn applies the In predicate on the "invitee_user_id" field.
func InviteeUserIDIn(vs ...int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldIn(FieldInviteeUserID, vs...))
}

// InviteeUserIDNotIn applies the NotIn predicate on the "invitee_user_id" field.
func InviteeUserIDNotIn(vs ...int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldNotIn(FieldInviteeUserID, vs...))
}

// InviteCodeIDEQ applies the EQ predicate on the "invite_code_id" field.
func InviteCodeIDEQ(v int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldEQ(FieldInviteCodeID, v))
}

// InviteCodeIDNEQ applies the NEQ predicate on the "invite_code_id" field.
func InviteCodeIDNEQ(v int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldNEQ(FieldInviteCodeID, v))
}

// InviteCodeIDIn applies the In predicate on the "invite_code_id" field.
func InviteCodeIDIn(vs ...int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldIn(FieldInviteCodeID, vs...))
}

// InviteCodeIDNotIn applies the NotIn predicate on the "invite_code_id" field.
func InviteCodeIDNotIn(vs ...int64) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldNotIn(FieldInviteCodeID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InviteBinding {
	return predicate.InviteBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// HasInviter applies the HasEdge predicate on the "inviter" edge.
func HasInviter() predicate.InviteBinding {
	return predicate.InviteBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InviterTable, InviterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInviterWith applies the HasEdge predicate on the "inviter" edge with a given conditions (other predicates).
func HasInviterWith(preds ...predicate.User) predicate.InviteBinding {
	return predicate.InviteBinding(func(s *sql.Selector) {
		step := newInviterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInvitee applies the HasEdge predicate on the "invitee" edge.
func HasInvitee() predicate.InviteBinding {
	return predicate.InviteBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InviteeTable, InviteeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInviteeWith applies the HasEdge predicate on the "invitee" edge with a given conditions (other predicates).
func HasInviteeWith(preds ...predicate.User) predicate.InviteBinding {
	return predicate.InviteBinding(func(s *sql.Selector) {
		step := newInviteeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInviteCode applies the HasEdge predicate on the "invite_code" edge.
func HasInviteCode() predicate.InviteBinding {
	return predicate.InviteBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InviteCodeTable, InviteCodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInviteCodeWith applies the HasEdge predicate on the "invite_code" edge with a given conditions (other predicates).
func HasInviteCodeWith(preds ...predicate.InviteCode) predicate.InviteBinding {
	return predicate.InviteBinding(func(s *sql.Selector) {
		step := newInviteCodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InviteBinding) predicate.InviteBinding {
	return predicate.InviteBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InviteBinding) predicate.InviteBinding {
	return predicate.InviteBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InviteBinding) predicate.InviteBinding {
	return predicate.InviteBinding(sql.NotPredicates(p))
}
